// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package contabo

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetInstanceSnapshot(ctx *pulumi.Context, args *GetInstanceSnapshotArgs, opts ...pulumi.InvokeOption) (*GetInstanceSnapshotResult, error) {
	var rv GetInstanceSnapshotResult
	err := ctx.Invoke("contabo:index/getInstanceSnapshot:getInstanceSnapshot", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getInstanceSnapshot.
type GetInstanceSnapshotArgs struct {
	Description *string `pulumi:"description"`
	Id          string  `pulumi:"id"`
	InstanceId  *string `pulumi:"instanceId"`
	Name        *string `pulumi:"name"`
}

// A collection of values returned by getInstanceSnapshot.
type GetInstanceSnapshotResult struct {
	AutoDeleteDate string  `pulumi:"autoDeleteDate"`
	CreatedDate    string  `pulumi:"createdDate"`
	Description    *string `pulumi:"description"`
	Id             string  `pulumi:"id"`
	ImageId        string  `pulumi:"imageId"`
	ImageName      string  `pulumi:"imageName"`
	InstanceId     *string `pulumi:"instanceId"`
	Name           *string `pulumi:"name"`
}

func GetInstanceSnapshotOutput(ctx *pulumi.Context, args GetInstanceSnapshotOutputArgs, opts ...pulumi.InvokeOption) GetInstanceSnapshotResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetInstanceSnapshotResult, error) {
			args := v.(GetInstanceSnapshotArgs)
			r, err := GetInstanceSnapshot(ctx, &args, opts...)
			var s GetInstanceSnapshotResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetInstanceSnapshotResultOutput)
}

// A collection of arguments for invoking getInstanceSnapshot.
type GetInstanceSnapshotOutputArgs struct {
	Description pulumi.StringPtrInput `pulumi:"description"`
	Id          pulumi.StringInput    `pulumi:"id"`
	InstanceId  pulumi.StringPtrInput `pulumi:"instanceId"`
	Name        pulumi.StringPtrInput `pulumi:"name"`
}

func (GetInstanceSnapshotOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInstanceSnapshotArgs)(nil)).Elem()
}

// A collection of values returned by getInstanceSnapshot.
type GetInstanceSnapshotResultOutput struct{ *pulumi.OutputState }

func (GetInstanceSnapshotResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInstanceSnapshotResult)(nil)).Elem()
}

func (o GetInstanceSnapshotResultOutput) ToGetInstanceSnapshotResultOutput() GetInstanceSnapshotResultOutput {
	return o
}

func (o GetInstanceSnapshotResultOutput) ToGetInstanceSnapshotResultOutputWithContext(ctx context.Context) GetInstanceSnapshotResultOutput {
	return o
}

func (o GetInstanceSnapshotResultOutput) AutoDeleteDate() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceSnapshotResult) string { return v.AutoDeleteDate }).(pulumi.StringOutput)
}

func (o GetInstanceSnapshotResultOutput) CreatedDate() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceSnapshotResult) string { return v.CreatedDate }).(pulumi.StringOutput)
}

func (o GetInstanceSnapshotResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetInstanceSnapshotResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

func (o GetInstanceSnapshotResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceSnapshotResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetInstanceSnapshotResultOutput) ImageId() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceSnapshotResult) string { return v.ImageId }).(pulumi.StringOutput)
}

func (o GetInstanceSnapshotResultOutput) ImageName() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceSnapshotResult) string { return v.ImageName }).(pulumi.StringOutput)
}

func (o GetInstanceSnapshotResultOutput) InstanceId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetInstanceSnapshotResult) *string { return v.InstanceId }).(pulumi.StringPtrOutput)
}

func (o GetInstanceSnapshotResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetInstanceSnapshotResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetInstanceSnapshotResultOutput{})
}
