// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package contabo

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetObjectStorageBucket(ctx *pulumi.Context, args *GetObjectStorageBucketArgs, opts ...pulumi.InvokeOption) (*GetObjectStorageBucketResult, error) {
	var rv GetObjectStorageBucketResult
	err := ctx.Invoke("contabo:index/getObjectStorageBucket:getObjectStorageBucket", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getObjectStorageBucket.
type GetObjectStorageBucketArgs struct {
	Name            string `pulumi:"name"`
	ObjectStorageId string `pulumi:"objectStorageId"`
	PublicSharing   *bool  `pulumi:"publicSharing"`
}

// A collection of values returned by getObjectStorageBucket.
type GetObjectStorageBucketResult struct {
	CreationDate string `pulumi:"creationDate"`
	// The provider-assigned unique ID for this managed resource.
	Id                string `pulumi:"id"`
	Name              string `pulumi:"name"`
	ObjectStorageId   string `pulumi:"objectStorageId"`
	PublicSharing     *bool  `pulumi:"publicSharing"`
	PublicSharingLink string `pulumi:"publicSharingLink"`
}

func GetObjectStorageBucketOutput(ctx *pulumi.Context, args GetObjectStorageBucketOutputArgs, opts ...pulumi.InvokeOption) GetObjectStorageBucketResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetObjectStorageBucketResult, error) {
			args := v.(GetObjectStorageBucketArgs)
			r, err := GetObjectStorageBucket(ctx, &args, opts...)
			var s GetObjectStorageBucketResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetObjectStorageBucketResultOutput)
}

// A collection of arguments for invoking getObjectStorageBucket.
type GetObjectStorageBucketOutputArgs struct {
	Name            pulumi.StringInput  `pulumi:"name"`
	ObjectStorageId pulumi.StringInput  `pulumi:"objectStorageId"`
	PublicSharing   pulumi.BoolPtrInput `pulumi:"publicSharing"`
}

func (GetObjectStorageBucketOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetObjectStorageBucketArgs)(nil)).Elem()
}

// A collection of values returned by getObjectStorageBucket.
type GetObjectStorageBucketResultOutput struct{ *pulumi.OutputState }

func (GetObjectStorageBucketResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetObjectStorageBucketResult)(nil)).Elem()
}

func (o GetObjectStorageBucketResultOutput) ToGetObjectStorageBucketResultOutput() GetObjectStorageBucketResultOutput {
	return o
}

func (o GetObjectStorageBucketResultOutput) ToGetObjectStorageBucketResultOutputWithContext(ctx context.Context) GetObjectStorageBucketResultOutput {
	return o
}

func (o GetObjectStorageBucketResultOutput) CreationDate() pulumi.StringOutput {
	return o.ApplyT(func(v GetObjectStorageBucketResult) string { return v.CreationDate }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetObjectStorageBucketResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetObjectStorageBucketResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetObjectStorageBucketResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetObjectStorageBucketResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetObjectStorageBucketResultOutput) ObjectStorageId() pulumi.StringOutput {
	return o.ApplyT(func(v GetObjectStorageBucketResult) string { return v.ObjectStorageId }).(pulumi.StringOutput)
}

func (o GetObjectStorageBucketResultOutput) PublicSharing() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetObjectStorageBucketResult) *bool { return v.PublicSharing }).(pulumi.BoolPtrOutput)
}

func (o GetObjectStorageBucketResultOutput) PublicSharingLink() pulumi.StringOutput {
	return o.ApplyT(func(v GetObjectStorageBucketResult) string { return v.PublicSharingLink }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetObjectStorageBucketResultOutput{})
}
