// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package contabo

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "contabo:index/image:image":
		r = &Image{}
	case "contabo:index/instance:instance":
		r = &Instance{}
	case "contabo:index/instance_snapshot:instance_snapshot":
		r = &Instance_snapshot{}
	case "contabo:index/object_storage:object_storage":
		r = &Object_storage{}
	case "contabo:index/object_storage_bucket:object_storage_bucket":
		r = &Object_storage_bucket{}
	case "contabo:index/private_network:private_network":
		r = &Private_network{}
	case "contabo:index/secret:secret":
		r = &Secret{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:contabo" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, _ := PkgVersion()
	pulumi.RegisterResourceModule(
		"contabo",
		"index/image",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"contabo",
		"index/instance",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"contabo",
		"index/instance_snapshot",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"contabo",
		"index/object_storage",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"contabo",
		"index/object_storage_bucket",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"contabo",
		"index/private_network",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"contabo",
		"index/secret",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"contabo",
		&pkg{version},
	)
}
