// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package contabo

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the contabo package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	// The api endpoint is https://api.contabo.com.
	Api pulumi.StringPtrOutput `pulumi:"api"`
	// Your oauth2 client id can be found in the [Customer Control Panel](https://new.contabo.com/account/security) under the
	// menu item account secret.
	Oauth2ClientId pulumi.StringPtrOutput `pulumi:"oauth2ClientId"`
	// Your oauth2 client secret can be found in the [Customer Control Panel](https://new.contabo.com/account/security) under
	// the menu item account secret.
	Oauth2ClientSecret pulumi.StringPtrOutput `pulumi:"oauth2ClientSecret"`
	// API Password (this is a new password which you'll set or change in the [Customer Control
	// Panel](https://new.contabo.com/account/security) under the menu item account secret.)
	Oauth2Pass pulumi.StringPtrOutput `pulumi:"oauth2Pass"`
	// The oauth2 token url is https://auth.contabo.com/auth/realms/contabo/protocol/openid-connect/token.
	Oauth2TokenUrl pulumi.StringPtrOutput `pulumi:"oauth2TokenUrl"`
	// API User (your email address to login to the [Customer Control Panel](https://new.contabo.com/account/security) under
	// the menu item account secret.
	Oauth2User pulumi.StringPtrOutput `pulumi:"oauth2User"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if args.Oauth2ClientId == nil {
		args.Oauth2ClientId = pulumi.StringPtr(getEnvOrDefault("", nil, "CONTABO_OAUTH2_CLIENT_ID").(string))
	}
	if args.Oauth2ClientSecret == nil {
		args.Oauth2ClientSecret = pulumi.StringPtr(getEnvOrDefault("", nil, "CONTABO_OAUTH2_CLIENT_SECRET").(string))
	}
	if args.Oauth2Pass == nil {
		args.Oauth2Pass = pulumi.StringPtr(getEnvOrDefault("", nil, "CONTABO_OAUTH2_PASS").(string))
	}
	if args.Oauth2User == nil {
		args.Oauth2User = pulumi.StringPtr(getEnvOrDefault("", nil, "CONTABO_OAUTH2_USER").(string))
	}
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:contabo", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// The api endpoint is https://api.contabo.com.
	Api *string `pulumi:"api"`
	// Your oauth2 client id can be found in the [Customer Control Panel](https://new.contabo.com/account/security) under the
	// menu item account secret.
	Oauth2ClientId *string `pulumi:"oauth2ClientId"`
	// Your oauth2 client secret can be found in the [Customer Control Panel](https://new.contabo.com/account/security) under
	// the menu item account secret.
	Oauth2ClientSecret *string `pulumi:"oauth2ClientSecret"`
	// API Password (this is a new password which you'll set or change in the [Customer Control
	// Panel](https://new.contabo.com/account/security) under the menu item account secret.)
	Oauth2Pass *string `pulumi:"oauth2Pass"`
	// The oauth2 token url is https://auth.contabo.com/auth/realms/contabo/protocol/openid-connect/token.
	Oauth2TokenUrl *string `pulumi:"oauth2TokenUrl"`
	// API User (your email address to login to the [Customer Control Panel](https://new.contabo.com/account/security) under
	// the menu item account secret.
	Oauth2User *string `pulumi:"oauth2User"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// The api endpoint is https://api.contabo.com.
	Api pulumi.StringPtrInput
	// Your oauth2 client id can be found in the [Customer Control Panel](https://new.contabo.com/account/security) under the
	// menu item account secret.
	Oauth2ClientId pulumi.StringPtrInput
	// Your oauth2 client secret can be found in the [Customer Control Panel](https://new.contabo.com/account/security) under
	// the menu item account secret.
	Oauth2ClientSecret pulumi.StringPtrInput
	// API Password (this is a new password which you'll set or change in the [Customer Control
	// Panel](https://new.contabo.com/account/security) under the menu item account secret.)
	Oauth2Pass pulumi.StringPtrInput
	// The oauth2 token url is https://auth.contabo.com/auth/realms/contabo/protocol/openid-connect/token.
	Oauth2TokenUrl pulumi.StringPtrInput
	// API User (your email address to login to the [Customer Control Panel](https://new.contabo.com/account/security) under
	// the menu item account secret.
	Oauth2User pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// The api endpoint is https://api.contabo.com.
func (o ProviderOutput) Api() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Api }).(pulumi.StringPtrOutput)
}

// Your oauth2 client id can be found in the [Customer Control Panel](https://new.contabo.com/account/security) under the
// menu item account secret.
func (o ProviderOutput) Oauth2ClientId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Oauth2ClientId }).(pulumi.StringPtrOutput)
}

// Your oauth2 client secret can be found in the [Customer Control Panel](https://new.contabo.com/account/security) under
// the menu item account secret.
func (o ProviderOutput) Oauth2ClientSecret() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Oauth2ClientSecret }).(pulumi.StringPtrOutput)
}

// API Password (this is a new password which you'll set or change in the [Customer Control
// Panel](https://new.contabo.com/account/security) under the menu item account secret.)
func (o ProviderOutput) Oauth2Pass() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Oauth2Pass }).(pulumi.StringPtrOutput)
}

// The oauth2 token url is https://auth.contabo.com/auth/realms/contabo/protocol/openid-connect/token.
func (o ProviderOutput) Oauth2TokenUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Oauth2TokenUrl }).(pulumi.StringPtrOutput)
}

// API User (your email address to login to the [Customer Control Panel](https://new.contabo.com/account/security) under
// the menu item account secret.
func (o ProviderOutput) Oauth2User() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Oauth2User }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
