// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package contabo

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type GetInstanceAddOn struct {
	Id       string `pulumi:"id"`
	Quantity int    `pulumi:"quantity"`
}

// GetInstanceAddOnInput is an input type that accepts GetInstanceAddOnArgs and GetInstanceAddOnOutput values.
// You can construct a concrete instance of `GetInstanceAddOnInput` via:
//
//	GetInstanceAddOnArgs{...}
type GetInstanceAddOnInput interface {
	pulumi.Input

	ToGetInstanceAddOnOutput() GetInstanceAddOnOutput
	ToGetInstanceAddOnOutputWithContext(context.Context) GetInstanceAddOnOutput
}

type GetInstanceAddOnArgs struct {
	Id       pulumi.StringInput `pulumi:"id"`
	Quantity pulumi.IntInput    `pulumi:"quantity"`
}

func (GetInstanceAddOnArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInstanceAddOn)(nil)).Elem()
}

func (i GetInstanceAddOnArgs) ToGetInstanceAddOnOutput() GetInstanceAddOnOutput {
	return i.ToGetInstanceAddOnOutputWithContext(context.Background())
}

func (i GetInstanceAddOnArgs) ToGetInstanceAddOnOutputWithContext(ctx context.Context) GetInstanceAddOnOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetInstanceAddOnOutput)
}

// GetInstanceAddOnArrayInput is an input type that accepts GetInstanceAddOnArray and GetInstanceAddOnArrayOutput values.
// You can construct a concrete instance of `GetInstanceAddOnArrayInput` via:
//
//	GetInstanceAddOnArray{ GetInstanceAddOnArgs{...} }
type GetInstanceAddOnArrayInput interface {
	pulumi.Input

	ToGetInstanceAddOnArrayOutput() GetInstanceAddOnArrayOutput
	ToGetInstanceAddOnArrayOutputWithContext(context.Context) GetInstanceAddOnArrayOutput
}

type GetInstanceAddOnArray []GetInstanceAddOnInput

func (GetInstanceAddOnArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetInstanceAddOn)(nil)).Elem()
}

func (i GetInstanceAddOnArray) ToGetInstanceAddOnArrayOutput() GetInstanceAddOnArrayOutput {
	return i.ToGetInstanceAddOnArrayOutputWithContext(context.Background())
}

func (i GetInstanceAddOnArray) ToGetInstanceAddOnArrayOutputWithContext(ctx context.Context) GetInstanceAddOnArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetInstanceAddOnArrayOutput)
}

type GetInstanceAddOnOutput struct{ *pulumi.OutputState }

func (GetInstanceAddOnOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInstanceAddOn)(nil)).Elem()
}

func (o GetInstanceAddOnOutput) ToGetInstanceAddOnOutput() GetInstanceAddOnOutput {
	return o
}

func (o GetInstanceAddOnOutput) ToGetInstanceAddOnOutputWithContext(ctx context.Context) GetInstanceAddOnOutput {
	return o
}

func (o GetInstanceAddOnOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceAddOn) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetInstanceAddOnOutput) Quantity() pulumi.IntOutput {
	return o.ApplyT(func(v GetInstanceAddOn) int { return v.Quantity }).(pulumi.IntOutput)
}

type GetInstanceAddOnArrayOutput struct{ *pulumi.OutputState }

func (GetInstanceAddOnArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetInstanceAddOn)(nil)).Elem()
}

func (o GetInstanceAddOnArrayOutput) ToGetInstanceAddOnArrayOutput() GetInstanceAddOnArrayOutput {
	return o
}

func (o GetInstanceAddOnArrayOutput) ToGetInstanceAddOnArrayOutputWithContext(ctx context.Context) GetInstanceAddOnArrayOutput {
	return o
}

func (o GetInstanceAddOnArrayOutput) Index(i pulumi.IntInput) GetInstanceAddOnOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetInstanceAddOn {
		return vs[0].([]GetInstanceAddOn)[vs[1].(int)]
	}).(GetInstanceAddOnOutput)
}

type GetInstanceAdditionalIpsV4 struct {
	Gateway     string `pulumi:"gateway"`
	Ip          string `pulumi:"ip"`
	NetmaskCidr int    `pulumi:"netmaskCidr"`
}

// GetInstanceAdditionalIpsV4Input is an input type that accepts GetInstanceAdditionalIpsV4Args and GetInstanceAdditionalIpsV4Output values.
// You can construct a concrete instance of `GetInstanceAdditionalIpsV4Input` via:
//
//	GetInstanceAdditionalIpsV4Args{...}
type GetInstanceAdditionalIpsV4Input interface {
	pulumi.Input

	ToGetInstanceAdditionalIpsV4Output() GetInstanceAdditionalIpsV4Output
	ToGetInstanceAdditionalIpsV4OutputWithContext(context.Context) GetInstanceAdditionalIpsV4Output
}

type GetInstanceAdditionalIpsV4Args struct {
	Gateway     pulumi.StringInput `pulumi:"gateway"`
	Ip          pulumi.StringInput `pulumi:"ip"`
	NetmaskCidr pulumi.IntInput    `pulumi:"netmaskCidr"`
}

func (GetInstanceAdditionalIpsV4Args) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInstanceAdditionalIpsV4)(nil)).Elem()
}

func (i GetInstanceAdditionalIpsV4Args) ToGetInstanceAdditionalIpsV4Output() GetInstanceAdditionalIpsV4Output {
	return i.ToGetInstanceAdditionalIpsV4OutputWithContext(context.Background())
}

func (i GetInstanceAdditionalIpsV4Args) ToGetInstanceAdditionalIpsV4OutputWithContext(ctx context.Context) GetInstanceAdditionalIpsV4Output {
	return pulumi.ToOutputWithContext(ctx, i).(GetInstanceAdditionalIpsV4Output)
}

// GetInstanceAdditionalIpsV4ArrayInput is an input type that accepts GetInstanceAdditionalIpsV4Array and GetInstanceAdditionalIpsV4ArrayOutput values.
// You can construct a concrete instance of `GetInstanceAdditionalIpsV4ArrayInput` via:
//
//	GetInstanceAdditionalIpsV4Array{ GetInstanceAdditionalIpsV4Args{...} }
type GetInstanceAdditionalIpsV4ArrayInput interface {
	pulumi.Input

	ToGetInstanceAdditionalIpsV4ArrayOutput() GetInstanceAdditionalIpsV4ArrayOutput
	ToGetInstanceAdditionalIpsV4ArrayOutputWithContext(context.Context) GetInstanceAdditionalIpsV4ArrayOutput
}

type GetInstanceAdditionalIpsV4Array []GetInstanceAdditionalIpsV4Input

func (GetInstanceAdditionalIpsV4Array) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetInstanceAdditionalIpsV4)(nil)).Elem()
}

func (i GetInstanceAdditionalIpsV4Array) ToGetInstanceAdditionalIpsV4ArrayOutput() GetInstanceAdditionalIpsV4ArrayOutput {
	return i.ToGetInstanceAdditionalIpsV4ArrayOutputWithContext(context.Background())
}

func (i GetInstanceAdditionalIpsV4Array) ToGetInstanceAdditionalIpsV4ArrayOutputWithContext(ctx context.Context) GetInstanceAdditionalIpsV4ArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetInstanceAdditionalIpsV4ArrayOutput)
}

type GetInstanceAdditionalIpsV4Output struct{ *pulumi.OutputState }

func (GetInstanceAdditionalIpsV4Output) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInstanceAdditionalIpsV4)(nil)).Elem()
}

func (o GetInstanceAdditionalIpsV4Output) ToGetInstanceAdditionalIpsV4Output() GetInstanceAdditionalIpsV4Output {
	return o
}

func (o GetInstanceAdditionalIpsV4Output) ToGetInstanceAdditionalIpsV4OutputWithContext(ctx context.Context) GetInstanceAdditionalIpsV4Output {
	return o
}

func (o GetInstanceAdditionalIpsV4Output) Gateway() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceAdditionalIpsV4) string { return v.Gateway }).(pulumi.StringOutput)
}

func (o GetInstanceAdditionalIpsV4Output) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceAdditionalIpsV4) string { return v.Ip }).(pulumi.StringOutput)
}

func (o GetInstanceAdditionalIpsV4Output) NetmaskCidr() pulumi.IntOutput {
	return o.ApplyT(func(v GetInstanceAdditionalIpsV4) int { return v.NetmaskCidr }).(pulumi.IntOutput)
}

type GetInstanceAdditionalIpsV4ArrayOutput struct{ *pulumi.OutputState }

func (GetInstanceAdditionalIpsV4ArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetInstanceAdditionalIpsV4)(nil)).Elem()
}

func (o GetInstanceAdditionalIpsV4ArrayOutput) ToGetInstanceAdditionalIpsV4ArrayOutput() GetInstanceAdditionalIpsV4ArrayOutput {
	return o
}

func (o GetInstanceAdditionalIpsV4ArrayOutput) ToGetInstanceAdditionalIpsV4ArrayOutputWithContext(ctx context.Context) GetInstanceAdditionalIpsV4ArrayOutput {
	return o
}

func (o GetInstanceAdditionalIpsV4ArrayOutput) Index(i pulumi.IntInput) GetInstanceAdditionalIpsV4Output {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetInstanceAdditionalIpsV4 {
		return vs[0].([]GetInstanceAdditionalIpsV4)[vs[1].(int)]
	}).(GetInstanceAdditionalIpsV4Output)
}

type GetInstanceIpConfig struct {
	V4s []GetInstanceIpConfigV4 `pulumi:"v4s"`
	V6s []GetInstanceIpConfigV6 `pulumi:"v6s"`
}

// GetInstanceIpConfigInput is an input type that accepts GetInstanceIpConfigArgs and GetInstanceIpConfigOutput values.
// You can construct a concrete instance of `GetInstanceIpConfigInput` via:
//
//	GetInstanceIpConfigArgs{...}
type GetInstanceIpConfigInput interface {
	pulumi.Input

	ToGetInstanceIpConfigOutput() GetInstanceIpConfigOutput
	ToGetInstanceIpConfigOutputWithContext(context.Context) GetInstanceIpConfigOutput
}

type GetInstanceIpConfigArgs struct {
	V4s GetInstanceIpConfigV4ArrayInput `pulumi:"v4s"`
	V6s GetInstanceIpConfigV6ArrayInput `pulumi:"v6s"`
}

func (GetInstanceIpConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInstanceIpConfig)(nil)).Elem()
}

func (i GetInstanceIpConfigArgs) ToGetInstanceIpConfigOutput() GetInstanceIpConfigOutput {
	return i.ToGetInstanceIpConfigOutputWithContext(context.Background())
}

func (i GetInstanceIpConfigArgs) ToGetInstanceIpConfigOutputWithContext(ctx context.Context) GetInstanceIpConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetInstanceIpConfigOutput)
}

// GetInstanceIpConfigArrayInput is an input type that accepts GetInstanceIpConfigArray and GetInstanceIpConfigArrayOutput values.
// You can construct a concrete instance of `GetInstanceIpConfigArrayInput` via:
//
//	GetInstanceIpConfigArray{ GetInstanceIpConfigArgs{...} }
type GetInstanceIpConfigArrayInput interface {
	pulumi.Input

	ToGetInstanceIpConfigArrayOutput() GetInstanceIpConfigArrayOutput
	ToGetInstanceIpConfigArrayOutputWithContext(context.Context) GetInstanceIpConfigArrayOutput
}

type GetInstanceIpConfigArray []GetInstanceIpConfigInput

func (GetInstanceIpConfigArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetInstanceIpConfig)(nil)).Elem()
}

func (i GetInstanceIpConfigArray) ToGetInstanceIpConfigArrayOutput() GetInstanceIpConfigArrayOutput {
	return i.ToGetInstanceIpConfigArrayOutputWithContext(context.Background())
}

func (i GetInstanceIpConfigArray) ToGetInstanceIpConfigArrayOutputWithContext(ctx context.Context) GetInstanceIpConfigArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetInstanceIpConfigArrayOutput)
}

type GetInstanceIpConfigOutput struct{ *pulumi.OutputState }

func (GetInstanceIpConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInstanceIpConfig)(nil)).Elem()
}

func (o GetInstanceIpConfigOutput) ToGetInstanceIpConfigOutput() GetInstanceIpConfigOutput {
	return o
}

func (o GetInstanceIpConfigOutput) ToGetInstanceIpConfigOutputWithContext(ctx context.Context) GetInstanceIpConfigOutput {
	return o
}

func (o GetInstanceIpConfigOutput) V4s() GetInstanceIpConfigV4ArrayOutput {
	return o.ApplyT(func(v GetInstanceIpConfig) []GetInstanceIpConfigV4 { return v.V4s }).(GetInstanceIpConfigV4ArrayOutput)
}

func (o GetInstanceIpConfigOutput) V6s() GetInstanceIpConfigV6ArrayOutput {
	return o.ApplyT(func(v GetInstanceIpConfig) []GetInstanceIpConfigV6 { return v.V6s }).(GetInstanceIpConfigV6ArrayOutput)
}

type GetInstanceIpConfigArrayOutput struct{ *pulumi.OutputState }

func (GetInstanceIpConfigArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetInstanceIpConfig)(nil)).Elem()
}

func (o GetInstanceIpConfigArrayOutput) ToGetInstanceIpConfigArrayOutput() GetInstanceIpConfigArrayOutput {
	return o
}

func (o GetInstanceIpConfigArrayOutput) ToGetInstanceIpConfigArrayOutputWithContext(ctx context.Context) GetInstanceIpConfigArrayOutput {
	return o
}

func (o GetInstanceIpConfigArrayOutput) Index(i pulumi.IntInput) GetInstanceIpConfigOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetInstanceIpConfig {
		return vs[0].([]GetInstanceIpConfig)[vs[1].(int)]
	}).(GetInstanceIpConfigOutput)
}

type GetInstanceIpConfigV4 struct {
	Gateway     string `pulumi:"gateway"`
	Ip          string `pulumi:"ip"`
	NetmaskCidr int    `pulumi:"netmaskCidr"`
}

// GetInstanceIpConfigV4Input is an input type that accepts GetInstanceIpConfigV4Args and GetInstanceIpConfigV4Output values.
// You can construct a concrete instance of `GetInstanceIpConfigV4Input` via:
//
//	GetInstanceIpConfigV4Args{...}
type GetInstanceIpConfigV4Input interface {
	pulumi.Input

	ToGetInstanceIpConfigV4Output() GetInstanceIpConfigV4Output
	ToGetInstanceIpConfigV4OutputWithContext(context.Context) GetInstanceIpConfigV4Output
}

type GetInstanceIpConfigV4Args struct {
	Gateway     pulumi.StringInput `pulumi:"gateway"`
	Ip          pulumi.StringInput `pulumi:"ip"`
	NetmaskCidr pulumi.IntInput    `pulumi:"netmaskCidr"`
}

func (GetInstanceIpConfigV4Args) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInstanceIpConfigV4)(nil)).Elem()
}

func (i GetInstanceIpConfigV4Args) ToGetInstanceIpConfigV4Output() GetInstanceIpConfigV4Output {
	return i.ToGetInstanceIpConfigV4OutputWithContext(context.Background())
}

func (i GetInstanceIpConfigV4Args) ToGetInstanceIpConfigV4OutputWithContext(ctx context.Context) GetInstanceIpConfigV4Output {
	return pulumi.ToOutputWithContext(ctx, i).(GetInstanceIpConfigV4Output)
}

// GetInstanceIpConfigV4ArrayInput is an input type that accepts GetInstanceIpConfigV4Array and GetInstanceIpConfigV4ArrayOutput values.
// You can construct a concrete instance of `GetInstanceIpConfigV4ArrayInput` via:
//
//	GetInstanceIpConfigV4Array{ GetInstanceIpConfigV4Args{...} }
type GetInstanceIpConfigV4ArrayInput interface {
	pulumi.Input

	ToGetInstanceIpConfigV4ArrayOutput() GetInstanceIpConfigV4ArrayOutput
	ToGetInstanceIpConfigV4ArrayOutputWithContext(context.Context) GetInstanceIpConfigV4ArrayOutput
}

type GetInstanceIpConfigV4Array []GetInstanceIpConfigV4Input

func (GetInstanceIpConfigV4Array) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetInstanceIpConfigV4)(nil)).Elem()
}

func (i GetInstanceIpConfigV4Array) ToGetInstanceIpConfigV4ArrayOutput() GetInstanceIpConfigV4ArrayOutput {
	return i.ToGetInstanceIpConfigV4ArrayOutputWithContext(context.Background())
}

func (i GetInstanceIpConfigV4Array) ToGetInstanceIpConfigV4ArrayOutputWithContext(ctx context.Context) GetInstanceIpConfigV4ArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetInstanceIpConfigV4ArrayOutput)
}

type GetInstanceIpConfigV4Output struct{ *pulumi.OutputState }

func (GetInstanceIpConfigV4Output) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInstanceIpConfigV4)(nil)).Elem()
}

func (o GetInstanceIpConfigV4Output) ToGetInstanceIpConfigV4Output() GetInstanceIpConfigV4Output {
	return o
}

func (o GetInstanceIpConfigV4Output) ToGetInstanceIpConfigV4OutputWithContext(ctx context.Context) GetInstanceIpConfigV4Output {
	return o
}

func (o GetInstanceIpConfigV4Output) Gateway() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceIpConfigV4) string { return v.Gateway }).(pulumi.StringOutput)
}

func (o GetInstanceIpConfigV4Output) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceIpConfigV4) string { return v.Ip }).(pulumi.StringOutput)
}

func (o GetInstanceIpConfigV4Output) NetmaskCidr() pulumi.IntOutput {
	return o.ApplyT(func(v GetInstanceIpConfigV4) int { return v.NetmaskCidr }).(pulumi.IntOutput)
}

type GetInstanceIpConfigV4ArrayOutput struct{ *pulumi.OutputState }

func (GetInstanceIpConfigV4ArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetInstanceIpConfigV4)(nil)).Elem()
}

func (o GetInstanceIpConfigV4ArrayOutput) ToGetInstanceIpConfigV4ArrayOutput() GetInstanceIpConfigV4ArrayOutput {
	return o
}

func (o GetInstanceIpConfigV4ArrayOutput) ToGetInstanceIpConfigV4ArrayOutputWithContext(ctx context.Context) GetInstanceIpConfigV4ArrayOutput {
	return o
}

func (o GetInstanceIpConfigV4ArrayOutput) Index(i pulumi.IntInput) GetInstanceIpConfigV4Output {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetInstanceIpConfigV4 {
		return vs[0].([]GetInstanceIpConfigV4)[vs[1].(int)]
	}).(GetInstanceIpConfigV4Output)
}

type GetInstanceIpConfigV6 struct {
	Gateway     string `pulumi:"gateway"`
	Ip          string `pulumi:"ip"`
	NetmaskCidr int    `pulumi:"netmaskCidr"`
}

// GetInstanceIpConfigV6Input is an input type that accepts GetInstanceIpConfigV6Args and GetInstanceIpConfigV6Output values.
// You can construct a concrete instance of `GetInstanceIpConfigV6Input` via:
//
//	GetInstanceIpConfigV6Args{...}
type GetInstanceIpConfigV6Input interface {
	pulumi.Input

	ToGetInstanceIpConfigV6Output() GetInstanceIpConfigV6Output
	ToGetInstanceIpConfigV6OutputWithContext(context.Context) GetInstanceIpConfigV6Output
}

type GetInstanceIpConfigV6Args struct {
	Gateway     pulumi.StringInput `pulumi:"gateway"`
	Ip          pulumi.StringInput `pulumi:"ip"`
	NetmaskCidr pulumi.IntInput    `pulumi:"netmaskCidr"`
}

func (GetInstanceIpConfigV6Args) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInstanceIpConfigV6)(nil)).Elem()
}

func (i GetInstanceIpConfigV6Args) ToGetInstanceIpConfigV6Output() GetInstanceIpConfigV6Output {
	return i.ToGetInstanceIpConfigV6OutputWithContext(context.Background())
}

func (i GetInstanceIpConfigV6Args) ToGetInstanceIpConfigV6OutputWithContext(ctx context.Context) GetInstanceIpConfigV6Output {
	return pulumi.ToOutputWithContext(ctx, i).(GetInstanceIpConfigV6Output)
}

// GetInstanceIpConfigV6ArrayInput is an input type that accepts GetInstanceIpConfigV6Array and GetInstanceIpConfigV6ArrayOutput values.
// You can construct a concrete instance of `GetInstanceIpConfigV6ArrayInput` via:
//
//	GetInstanceIpConfigV6Array{ GetInstanceIpConfigV6Args{...} }
type GetInstanceIpConfigV6ArrayInput interface {
	pulumi.Input

	ToGetInstanceIpConfigV6ArrayOutput() GetInstanceIpConfigV6ArrayOutput
	ToGetInstanceIpConfigV6ArrayOutputWithContext(context.Context) GetInstanceIpConfigV6ArrayOutput
}

type GetInstanceIpConfigV6Array []GetInstanceIpConfigV6Input

func (GetInstanceIpConfigV6Array) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetInstanceIpConfigV6)(nil)).Elem()
}

func (i GetInstanceIpConfigV6Array) ToGetInstanceIpConfigV6ArrayOutput() GetInstanceIpConfigV6ArrayOutput {
	return i.ToGetInstanceIpConfigV6ArrayOutputWithContext(context.Background())
}

func (i GetInstanceIpConfigV6Array) ToGetInstanceIpConfigV6ArrayOutputWithContext(ctx context.Context) GetInstanceIpConfigV6ArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetInstanceIpConfigV6ArrayOutput)
}

type GetInstanceIpConfigV6Output struct{ *pulumi.OutputState }

func (GetInstanceIpConfigV6Output) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInstanceIpConfigV6)(nil)).Elem()
}

func (o GetInstanceIpConfigV6Output) ToGetInstanceIpConfigV6Output() GetInstanceIpConfigV6Output {
	return o
}

func (o GetInstanceIpConfigV6Output) ToGetInstanceIpConfigV6OutputWithContext(ctx context.Context) GetInstanceIpConfigV6Output {
	return o
}

func (o GetInstanceIpConfigV6Output) Gateway() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceIpConfigV6) string { return v.Gateway }).(pulumi.StringOutput)
}

func (o GetInstanceIpConfigV6Output) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceIpConfigV6) string { return v.Ip }).(pulumi.StringOutput)
}

func (o GetInstanceIpConfigV6Output) NetmaskCidr() pulumi.IntOutput {
	return o.ApplyT(func(v GetInstanceIpConfigV6) int { return v.NetmaskCidr }).(pulumi.IntOutput)
}

type GetInstanceIpConfigV6ArrayOutput struct{ *pulumi.OutputState }

func (GetInstanceIpConfigV6ArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetInstanceIpConfigV6)(nil)).Elem()
}

func (o GetInstanceIpConfigV6ArrayOutput) ToGetInstanceIpConfigV6ArrayOutput() GetInstanceIpConfigV6ArrayOutput {
	return o
}

func (o GetInstanceIpConfigV6ArrayOutput) ToGetInstanceIpConfigV6ArrayOutputWithContext(ctx context.Context) GetInstanceIpConfigV6ArrayOutput {
	return o
}

func (o GetInstanceIpConfigV6ArrayOutput) Index(i pulumi.IntInput) GetInstanceIpConfigV6Output {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetInstanceIpConfigV6 {
		return vs[0].([]GetInstanceIpConfigV6)[vs[1].(int)]
	}).(GetInstanceIpConfigV6Output)
}

type GetObjectStorageAutoScaling struct {
	ErrorMessage string  `pulumi:"errorMessage"`
	SizeLimitTb  float64 `pulumi:"sizeLimitTb"`
	State        string  `pulumi:"state"`
}

// GetObjectStorageAutoScalingInput is an input type that accepts GetObjectStorageAutoScalingArgs and GetObjectStorageAutoScalingOutput values.
// You can construct a concrete instance of `GetObjectStorageAutoScalingInput` via:
//
//	GetObjectStorageAutoScalingArgs{...}
type GetObjectStorageAutoScalingInput interface {
	pulumi.Input

	ToGetObjectStorageAutoScalingOutput() GetObjectStorageAutoScalingOutput
	ToGetObjectStorageAutoScalingOutputWithContext(context.Context) GetObjectStorageAutoScalingOutput
}

type GetObjectStorageAutoScalingArgs struct {
	ErrorMessage pulumi.StringInput  `pulumi:"errorMessage"`
	SizeLimitTb  pulumi.Float64Input `pulumi:"sizeLimitTb"`
	State        pulumi.StringInput  `pulumi:"state"`
}

func (GetObjectStorageAutoScalingArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetObjectStorageAutoScaling)(nil)).Elem()
}

func (i GetObjectStorageAutoScalingArgs) ToGetObjectStorageAutoScalingOutput() GetObjectStorageAutoScalingOutput {
	return i.ToGetObjectStorageAutoScalingOutputWithContext(context.Background())
}

func (i GetObjectStorageAutoScalingArgs) ToGetObjectStorageAutoScalingOutputWithContext(ctx context.Context) GetObjectStorageAutoScalingOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetObjectStorageAutoScalingOutput)
}

// GetObjectStorageAutoScalingArrayInput is an input type that accepts GetObjectStorageAutoScalingArray and GetObjectStorageAutoScalingArrayOutput values.
// You can construct a concrete instance of `GetObjectStorageAutoScalingArrayInput` via:
//
//	GetObjectStorageAutoScalingArray{ GetObjectStorageAutoScalingArgs{...} }
type GetObjectStorageAutoScalingArrayInput interface {
	pulumi.Input

	ToGetObjectStorageAutoScalingArrayOutput() GetObjectStorageAutoScalingArrayOutput
	ToGetObjectStorageAutoScalingArrayOutputWithContext(context.Context) GetObjectStorageAutoScalingArrayOutput
}

type GetObjectStorageAutoScalingArray []GetObjectStorageAutoScalingInput

func (GetObjectStorageAutoScalingArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetObjectStorageAutoScaling)(nil)).Elem()
}

func (i GetObjectStorageAutoScalingArray) ToGetObjectStorageAutoScalingArrayOutput() GetObjectStorageAutoScalingArrayOutput {
	return i.ToGetObjectStorageAutoScalingArrayOutputWithContext(context.Background())
}

func (i GetObjectStorageAutoScalingArray) ToGetObjectStorageAutoScalingArrayOutputWithContext(ctx context.Context) GetObjectStorageAutoScalingArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetObjectStorageAutoScalingArrayOutput)
}

type GetObjectStorageAutoScalingOutput struct{ *pulumi.OutputState }

func (GetObjectStorageAutoScalingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetObjectStorageAutoScaling)(nil)).Elem()
}

func (o GetObjectStorageAutoScalingOutput) ToGetObjectStorageAutoScalingOutput() GetObjectStorageAutoScalingOutput {
	return o
}

func (o GetObjectStorageAutoScalingOutput) ToGetObjectStorageAutoScalingOutputWithContext(ctx context.Context) GetObjectStorageAutoScalingOutput {
	return o
}

func (o GetObjectStorageAutoScalingOutput) ErrorMessage() pulumi.StringOutput {
	return o.ApplyT(func(v GetObjectStorageAutoScaling) string { return v.ErrorMessage }).(pulumi.StringOutput)
}

func (o GetObjectStorageAutoScalingOutput) SizeLimitTb() pulumi.Float64Output {
	return o.ApplyT(func(v GetObjectStorageAutoScaling) float64 { return v.SizeLimitTb }).(pulumi.Float64Output)
}

func (o GetObjectStorageAutoScalingOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v GetObjectStorageAutoScaling) string { return v.State }).(pulumi.StringOutput)
}

type GetObjectStorageAutoScalingArrayOutput struct{ *pulumi.OutputState }

func (GetObjectStorageAutoScalingArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetObjectStorageAutoScaling)(nil)).Elem()
}

func (o GetObjectStorageAutoScalingArrayOutput) ToGetObjectStorageAutoScalingArrayOutput() GetObjectStorageAutoScalingArrayOutput {
	return o
}

func (o GetObjectStorageAutoScalingArrayOutput) ToGetObjectStorageAutoScalingArrayOutputWithContext(ctx context.Context) GetObjectStorageAutoScalingArrayOutput {
	return o
}

func (o GetObjectStorageAutoScalingArrayOutput) Index(i pulumi.IntInput) GetObjectStorageAutoScalingOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetObjectStorageAutoScaling {
		return vs[0].([]GetObjectStorageAutoScaling)[vs[1].(int)]
	}).(GetObjectStorageAutoScalingOutput)
}

type GetPrivateNetworkInstance struct {
	DisplayName      string                                     `pulumi:"displayName"`
	ErrorMessage     string                                     `pulumi:"errorMessage"`
	InstanceId       string                                     `pulumi:"instanceId"`
	Name             string                                     `pulumi:"name"`
	PrivateIpConfigs []GetPrivateNetworkInstancePrivateIpConfig `pulumi:"privateIpConfigs"`
	Status           string                                     `pulumi:"status"`
}

// GetPrivateNetworkInstanceInput is an input type that accepts GetPrivateNetworkInstanceArgs and GetPrivateNetworkInstanceOutput values.
// You can construct a concrete instance of `GetPrivateNetworkInstanceInput` via:
//
//	GetPrivateNetworkInstanceArgs{...}
type GetPrivateNetworkInstanceInput interface {
	pulumi.Input

	ToGetPrivateNetworkInstanceOutput() GetPrivateNetworkInstanceOutput
	ToGetPrivateNetworkInstanceOutputWithContext(context.Context) GetPrivateNetworkInstanceOutput
}

type GetPrivateNetworkInstanceArgs struct {
	DisplayName      pulumi.StringInput                                 `pulumi:"displayName"`
	ErrorMessage     pulumi.StringInput                                 `pulumi:"errorMessage"`
	InstanceId       pulumi.StringInput                                 `pulumi:"instanceId"`
	Name             pulumi.StringInput                                 `pulumi:"name"`
	PrivateIpConfigs GetPrivateNetworkInstancePrivateIpConfigArrayInput `pulumi:"privateIpConfigs"`
	Status           pulumi.StringInput                                 `pulumi:"status"`
}

func (GetPrivateNetworkInstanceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPrivateNetworkInstance)(nil)).Elem()
}

func (i GetPrivateNetworkInstanceArgs) ToGetPrivateNetworkInstanceOutput() GetPrivateNetworkInstanceOutput {
	return i.ToGetPrivateNetworkInstanceOutputWithContext(context.Background())
}

func (i GetPrivateNetworkInstanceArgs) ToGetPrivateNetworkInstanceOutputWithContext(ctx context.Context) GetPrivateNetworkInstanceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPrivateNetworkInstanceOutput)
}

// GetPrivateNetworkInstanceArrayInput is an input type that accepts GetPrivateNetworkInstanceArray and GetPrivateNetworkInstanceArrayOutput values.
// You can construct a concrete instance of `GetPrivateNetworkInstanceArrayInput` via:
//
//	GetPrivateNetworkInstanceArray{ GetPrivateNetworkInstanceArgs{...} }
type GetPrivateNetworkInstanceArrayInput interface {
	pulumi.Input

	ToGetPrivateNetworkInstanceArrayOutput() GetPrivateNetworkInstanceArrayOutput
	ToGetPrivateNetworkInstanceArrayOutputWithContext(context.Context) GetPrivateNetworkInstanceArrayOutput
}

type GetPrivateNetworkInstanceArray []GetPrivateNetworkInstanceInput

func (GetPrivateNetworkInstanceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPrivateNetworkInstance)(nil)).Elem()
}

func (i GetPrivateNetworkInstanceArray) ToGetPrivateNetworkInstanceArrayOutput() GetPrivateNetworkInstanceArrayOutput {
	return i.ToGetPrivateNetworkInstanceArrayOutputWithContext(context.Background())
}

func (i GetPrivateNetworkInstanceArray) ToGetPrivateNetworkInstanceArrayOutputWithContext(ctx context.Context) GetPrivateNetworkInstanceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPrivateNetworkInstanceArrayOutput)
}

type GetPrivateNetworkInstanceOutput struct{ *pulumi.OutputState }

func (GetPrivateNetworkInstanceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPrivateNetworkInstance)(nil)).Elem()
}

func (o GetPrivateNetworkInstanceOutput) ToGetPrivateNetworkInstanceOutput() GetPrivateNetworkInstanceOutput {
	return o
}

func (o GetPrivateNetworkInstanceOutput) ToGetPrivateNetworkInstanceOutputWithContext(ctx context.Context) GetPrivateNetworkInstanceOutput {
	return o
}

func (o GetPrivateNetworkInstanceOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrivateNetworkInstance) string { return v.DisplayName }).(pulumi.StringOutput)
}

func (o GetPrivateNetworkInstanceOutput) ErrorMessage() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrivateNetworkInstance) string { return v.ErrorMessage }).(pulumi.StringOutput)
}

func (o GetPrivateNetworkInstanceOutput) InstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrivateNetworkInstance) string { return v.InstanceId }).(pulumi.StringOutput)
}

func (o GetPrivateNetworkInstanceOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrivateNetworkInstance) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetPrivateNetworkInstanceOutput) PrivateIpConfigs() GetPrivateNetworkInstancePrivateIpConfigArrayOutput {
	return o.ApplyT(func(v GetPrivateNetworkInstance) []GetPrivateNetworkInstancePrivateIpConfig {
		return v.PrivateIpConfigs
	}).(GetPrivateNetworkInstancePrivateIpConfigArrayOutput)
}

func (o GetPrivateNetworkInstanceOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrivateNetworkInstance) string { return v.Status }).(pulumi.StringOutput)
}

type GetPrivateNetworkInstanceArrayOutput struct{ *pulumi.OutputState }

func (GetPrivateNetworkInstanceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPrivateNetworkInstance)(nil)).Elem()
}

func (o GetPrivateNetworkInstanceArrayOutput) ToGetPrivateNetworkInstanceArrayOutput() GetPrivateNetworkInstanceArrayOutput {
	return o
}

func (o GetPrivateNetworkInstanceArrayOutput) ToGetPrivateNetworkInstanceArrayOutputWithContext(ctx context.Context) GetPrivateNetworkInstanceArrayOutput {
	return o
}

func (o GetPrivateNetworkInstanceArrayOutput) Index(i pulumi.IntInput) GetPrivateNetworkInstanceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetPrivateNetworkInstance {
		return vs[0].([]GetPrivateNetworkInstance)[vs[1].(int)]
	}).(GetPrivateNetworkInstanceOutput)
}

type GetPrivateNetworkInstancePrivateIpConfig struct {
	V4s []GetPrivateNetworkInstancePrivateIpConfigV4 `pulumi:"v4s"`
}

// GetPrivateNetworkInstancePrivateIpConfigInput is an input type that accepts GetPrivateNetworkInstancePrivateIpConfigArgs and GetPrivateNetworkInstancePrivateIpConfigOutput values.
// You can construct a concrete instance of `GetPrivateNetworkInstancePrivateIpConfigInput` via:
//
//	GetPrivateNetworkInstancePrivateIpConfigArgs{...}
type GetPrivateNetworkInstancePrivateIpConfigInput interface {
	pulumi.Input

	ToGetPrivateNetworkInstancePrivateIpConfigOutput() GetPrivateNetworkInstancePrivateIpConfigOutput
	ToGetPrivateNetworkInstancePrivateIpConfigOutputWithContext(context.Context) GetPrivateNetworkInstancePrivateIpConfigOutput
}

type GetPrivateNetworkInstancePrivateIpConfigArgs struct {
	V4s GetPrivateNetworkInstancePrivateIpConfigV4ArrayInput `pulumi:"v4s"`
}

func (GetPrivateNetworkInstancePrivateIpConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPrivateNetworkInstancePrivateIpConfig)(nil)).Elem()
}

func (i GetPrivateNetworkInstancePrivateIpConfigArgs) ToGetPrivateNetworkInstancePrivateIpConfigOutput() GetPrivateNetworkInstancePrivateIpConfigOutput {
	return i.ToGetPrivateNetworkInstancePrivateIpConfigOutputWithContext(context.Background())
}

func (i GetPrivateNetworkInstancePrivateIpConfigArgs) ToGetPrivateNetworkInstancePrivateIpConfigOutputWithContext(ctx context.Context) GetPrivateNetworkInstancePrivateIpConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPrivateNetworkInstancePrivateIpConfigOutput)
}

// GetPrivateNetworkInstancePrivateIpConfigArrayInput is an input type that accepts GetPrivateNetworkInstancePrivateIpConfigArray and GetPrivateNetworkInstancePrivateIpConfigArrayOutput values.
// You can construct a concrete instance of `GetPrivateNetworkInstancePrivateIpConfigArrayInput` via:
//
//	GetPrivateNetworkInstancePrivateIpConfigArray{ GetPrivateNetworkInstancePrivateIpConfigArgs{...} }
type GetPrivateNetworkInstancePrivateIpConfigArrayInput interface {
	pulumi.Input

	ToGetPrivateNetworkInstancePrivateIpConfigArrayOutput() GetPrivateNetworkInstancePrivateIpConfigArrayOutput
	ToGetPrivateNetworkInstancePrivateIpConfigArrayOutputWithContext(context.Context) GetPrivateNetworkInstancePrivateIpConfigArrayOutput
}

type GetPrivateNetworkInstancePrivateIpConfigArray []GetPrivateNetworkInstancePrivateIpConfigInput

func (GetPrivateNetworkInstancePrivateIpConfigArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPrivateNetworkInstancePrivateIpConfig)(nil)).Elem()
}

func (i GetPrivateNetworkInstancePrivateIpConfigArray) ToGetPrivateNetworkInstancePrivateIpConfigArrayOutput() GetPrivateNetworkInstancePrivateIpConfigArrayOutput {
	return i.ToGetPrivateNetworkInstancePrivateIpConfigArrayOutputWithContext(context.Background())
}

func (i GetPrivateNetworkInstancePrivateIpConfigArray) ToGetPrivateNetworkInstancePrivateIpConfigArrayOutputWithContext(ctx context.Context) GetPrivateNetworkInstancePrivateIpConfigArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPrivateNetworkInstancePrivateIpConfigArrayOutput)
}

type GetPrivateNetworkInstancePrivateIpConfigOutput struct{ *pulumi.OutputState }

func (GetPrivateNetworkInstancePrivateIpConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPrivateNetworkInstancePrivateIpConfig)(nil)).Elem()
}

func (o GetPrivateNetworkInstancePrivateIpConfigOutput) ToGetPrivateNetworkInstancePrivateIpConfigOutput() GetPrivateNetworkInstancePrivateIpConfigOutput {
	return o
}

func (o GetPrivateNetworkInstancePrivateIpConfigOutput) ToGetPrivateNetworkInstancePrivateIpConfigOutputWithContext(ctx context.Context) GetPrivateNetworkInstancePrivateIpConfigOutput {
	return o
}

func (o GetPrivateNetworkInstancePrivateIpConfigOutput) V4s() GetPrivateNetworkInstancePrivateIpConfigV4ArrayOutput {
	return o.ApplyT(func(v GetPrivateNetworkInstancePrivateIpConfig) []GetPrivateNetworkInstancePrivateIpConfigV4 {
		return v.V4s
	}).(GetPrivateNetworkInstancePrivateIpConfigV4ArrayOutput)
}

type GetPrivateNetworkInstancePrivateIpConfigArrayOutput struct{ *pulumi.OutputState }

func (GetPrivateNetworkInstancePrivateIpConfigArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPrivateNetworkInstancePrivateIpConfig)(nil)).Elem()
}

func (o GetPrivateNetworkInstancePrivateIpConfigArrayOutput) ToGetPrivateNetworkInstancePrivateIpConfigArrayOutput() GetPrivateNetworkInstancePrivateIpConfigArrayOutput {
	return o
}

func (o GetPrivateNetworkInstancePrivateIpConfigArrayOutput) ToGetPrivateNetworkInstancePrivateIpConfigArrayOutputWithContext(ctx context.Context) GetPrivateNetworkInstancePrivateIpConfigArrayOutput {
	return o
}

func (o GetPrivateNetworkInstancePrivateIpConfigArrayOutput) Index(i pulumi.IntInput) GetPrivateNetworkInstancePrivateIpConfigOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetPrivateNetworkInstancePrivateIpConfig {
		return vs[0].([]GetPrivateNetworkInstancePrivateIpConfig)[vs[1].(int)]
	}).(GetPrivateNetworkInstancePrivateIpConfigOutput)
}

type GetPrivateNetworkInstancePrivateIpConfigV4 struct {
	Gateway     string `pulumi:"gateway"`
	Ip          string `pulumi:"ip"`
	NetmaskCidr int    `pulumi:"netmaskCidr"`
}

// GetPrivateNetworkInstancePrivateIpConfigV4Input is an input type that accepts GetPrivateNetworkInstancePrivateIpConfigV4Args and GetPrivateNetworkInstancePrivateIpConfigV4Output values.
// You can construct a concrete instance of `GetPrivateNetworkInstancePrivateIpConfigV4Input` via:
//
//	GetPrivateNetworkInstancePrivateIpConfigV4Args{...}
type GetPrivateNetworkInstancePrivateIpConfigV4Input interface {
	pulumi.Input

	ToGetPrivateNetworkInstancePrivateIpConfigV4Output() GetPrivateNetworkInstancePrivateIpConfigV4Output
	ToGetPrivateNetworkInstancePrivateIpConfigV4OutputWithContext(context.Context) GetPrivateNetworkInstancePrivateIpConfigV4Output
}

type GetPrivateNetworkInstancePrivateIpConfigV4Args struct {
	Gateway     pulumi.StringInput `pulumi:"gateway"`
	Ip          pulumi.StringInput `pulumi:"ip"`
	NetmaskCidr pulumi.IntInput    `pulumi:"netmaskCidr"`
}

func (GetPrivateNetworkInstancePrivateIpConfigV4Args) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPrivateNetworkInstancePrivateIpConfigV4)(nil)).Elem()
}

func (i GetPrivateNetworkInstancePrivateIpConfigV4Args) ToGetPrivateNetworkInstancePrivateIpConfigV4Output() GetPrivateNetworkInstancePrivateIpConfigV4Output {
	return i.ToGetPrivateNetworkInstancePrivateIpConfigV4OutputWithContext(context.Background())
}

func (i GetPrivateNetworkInstancePrivateIpConfigV4Args) ToGetPrivateNetworkInstancePrivateIpConfigV4OutputWithContext(ctx context.Context) GetPrivateNetworkInstancePrivateIpConfigV4Output {
	return pulumi.ToOutputWithContext(ctx, i).(GetPrivateNetworkInstancePrivateIpConfigV4Output)
}

// GetPrivateNetworkInstancePrivateIpConfigV4ArrayInput is an input type that accepts GetPrivateNetworkInstancePrivateIpConfigV4Array and GetPrivateNetworkInstancePrivateIpConfigV4ArrayOutput values.
// You can construct a concrete instance of `GetPrivateNetworkInstancePrivateIpConfigV4ArrayInput` via:
//
//	GetPrivateNetworkInstancePrivateIpConfigV4Array{ GetPrivateNetworkInstancePrivateIpConfigV4Args{...} }
type GetPrivateNetworkInstancePrivateIpConfigV4ArrayInput interface {
	pulumi.Input

	ToGetPrivateNetworkInstancePrivateIpConfigV4ArrayOutput() GetPrivateNetworkInstancePrivateIpConfigV4ArrayOutput
	ToGetPrivateNetworkInstancePrivateIpConfigV4ArrayOutputWithContext(context.Context) GetPrivateNetworkInstancePrivateIpConfigV4ArrayOutput
}

type GetPrivateNetworkInstancePrivateIpConfigV4Array []GetPrivateNetworkInstancePrivateIpConfigV4Input

func (GetPrivateNetworkInstancePrivateIpConfigV4Array) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPrivateNetworkInstancePrivateIpConfigV4)(nil)).Elem()
}

func (i GetPrivateNetworkInstancePrivateIpConfigV4Array) ToGetPrivateNetworkInstancePrivateIpConfigV4ArrayOutput() GetPrivateNetworkInstancePrivateIpConfigV4ArrayOutput {
	return i.ToGetPrivateNetworkInstancePrivateIpConfigV4ArrayOutputWithContext(context.Background())
}

func (i GetPrivateNetworkInstancePrivateIpConfigV4Array) ToGetPrivateNetworkInstancePrivateIpConfigV4ArrayOutputWithContext(ctx context.Context) GetPrivateNetworkInstancePrivateIpConfigV4ArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPrivateNetworkInstancePrivateIpConfigV4ArrayOutput)
}

type GetPrivateNetworkInstancePrivateIpConfigV4Output struct{ *pulumi.OutputState }

func (GetPrivateNetworkInstancePrivateIpConfigV4Output) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPrivateNetworkInstancePrivateIpConfigV4)(nil)).Elem()
}

func (o GetPrivateNetworkInstancePrivateIpConfigV4Output) ToGetPrivateNetworkInstancePrivateIpConfigV4Output() GetPrivateNetworkInstancePrivateIpConfigV4Output {
	return o
}

func (o GetPrivateNetworkInstancePrivateIpConfigV4Output) ToGetPrivateNetworkInstancePrivateIpConfigV4OutputWithContext(ctx context.Context) GetPrivateNetworkInstancePrivateIpConfigV4Output {
	return o
}

func (o GetPrivateNetworkInstancePrivateIpConfigV4Output) Gateway() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrivateNetworkInstancePrivateIpConfigV4) string { return v.Gateway }).(pulumi.StringOutput)
}

func (o GetPrivateNetworkInstancePrivateIpConfigV4Output) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrivateNetworkInstancePrivateIpConfigV4) string { return v.Ip }).(pulumi.StringOutput)
}

func (o GetPrivateNetworkInstancePrivateIpConfigV4Output) NetmaskCidr() pulumi.IntOutput {
	return o.ApplyT(func(v GetPrivateNetworkInstancePrivateIpConfigV4) int { return v.NetmaskCidr }).(pulumi.IntOutput)
}

type GetPrivateNetworkInstancePrivateIpConfigV4ArrayOutput struct{ *pulumi.OutputState }

func (GetPrivateNetworkInstancePrivateIpConfigV4ArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPrivateNetworkInstancePrivateIpConfigV4)(nil)).Elem()
}

func (o GetPrivateNetworkInstancePrivateIpConfigV4ArrayOutput) ToGetPrivateNetworkInstancePrivateIpConfigV4ArrayOutput() GetPrivateNetworkInstancePrivateIpConfigV4ArrayOutput {
	return o
}

func (o GetPrivateNetworkInstancePrivateIpConfigV4ArrayOutput) ToGetPrivateNetworkInstancePrivateIpConfigV4ArrayOutputWithContext(ctx context.Context) GetPrivateNetworkInstancePrivateIpConfigV4ArrayOutput {
	return o
}

func (o GetPrivateNetworkInstancePrivateIpConfigV4ArrayOutput) Index(i pulumi.IntInput) GetPrivateNetworkInstancePrivateIpConfigV4Output {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetPrivateNetworkInstancePrivateIpConfigV4 {
		return vs[0].([]GetPrivateNetworkInstancePrivateIpConfigV4)[vs[1].(int)]
	}).(GetPrivateNetworkInstancePrivateIpConfigV4Output)
}

type InstanceAddOn struct {
	Id       *string `pulumi:"id"`
	Quantity *int    `pulumi:"quantity"`
}

// InstanceAddOnInput is an input type that accepts InstanceAddOnArgs and InstanceAddOnOutput values.
// You can construct a concrete instance of `InstanceAddOnInput` via:
//
//	InstanceAddOnArgs{...}
type InstanceAddOnInput interface {
	pulumi.Input

	ToInstanceAddOnOutput() InstanceAddOnOutput
	ToInstanceAddOnOutputWithContext(context.Context) InstanceAddOnOutput
}

type InstanceAddOnArgs struct {
	Id       pulumi.StringPtrInput `pulumi:"id"`
	Quantity pulumi.IntPtrInput    `pulumi:"quantity"`
}

func (InstanceAddOnArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*InstanceAddOn)(nil)).Elem()
}

func (i InstanceAddOnArgs) ToInstanceAddOnOutput() InstanceAddOnOutput {
	return i.ToInstanceAddOnOutputWithContext(context.Background())
}

func (i InstanceAddOnArgs) ToInstanceAddOnOutputWithContext(ctx context.Context) InstanceAddOnOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceAddOnOutput)
}

// InstanceAddOnArrayInput is an input type that accepts InstanceAddOnArray and InstanceAddOnArrayOutput values.
// You can construct a concrete instance of `InstanceAddOnArrayInput` via:
//
//	InstanceAddOnArray{ InstanceAddOnArgs{...} }
type InstanceAddOnArrayInput interface {
	pulumi.Input

	ToInstanceAddOnArrayOutput() InstanceAddOnArrayOutput
	ToInstanceAddOnArrayOutputWithContext(context.Context) InstanceAddOnArrayOutput
}

type InstanceAddOnArray []InstanceAddOnInput

func (InstanceAddOnArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]InstanceAddOn)(nil)).Elem()
}

func (i InstanceAddOnArray) ToInstanceAddOnArrayOutput() InstanceAddOnArrayOutput {
	return i.ToInstanceAddOnArrayOutputWithContext(context.Background())
}

func (i InstanceAddOnArray) ToInstanceAddOnArrayOutputWithContext(ctx context.Context) InstanceAddOnArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceAddOnArrayOutput)
}

type InstanceAddOnOutput struct{ *pulumi.OutputState }

func (InstanceAddOnOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*InstanceAddOn)(nil)).Elem()
}

func (o InstanceAddOnOutput) ToInstanceAddOnOutput() InstanceAddOnOutput {
	return o
}

func (o InstanceAddOnOutput) ToInstanceAddOnOutputWithContext(ctx context.Context) InstanceAddOnOutput {
	return o
}

func (o InstanceAddOnOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v InstanceAddOn) *string { return v.Id }).(pulumi.StringPtrOutput)
}

func (o InstanceAddOnOutput) Quantity() pulumi.IntPtrOutput {
	return o.ApplyT(func(v InstanceAddOn) *int { return v.Quantity }).(pulumi.IntPtrOutput)
}

type InstanceAddOnArrayOutput struct{ *pulumi.OutputState }

func (InstanceAddOnArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]InstanceAddOn)(nil)).Elem()
}

func (o InstanceAddOnArrayOutput) ToInstanceAddOnArrayOutput() InstanceAddOnArrayOutput {
	return o
}

func (o InstanceAddOnArrayOutput) ToInstanceAddOnArrayOutputWithContext(ctx context.Context) InstanceAddOnArrayOutput {
	return o
}

func (o InstanceAddOnArrayOutput) Index(i pulumi.IntInput) InstanceAddOnOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) InstanceAddOn {
		return vs[0].([]InstanceAddOn)[vs[1].(int)]
	}).(InstanceAddOnOutput)
}

type InstanceAdditionalIp struct {
	V4s []InstanceAdditionalIpV4 `pulumi:"v4s"`
}

// InstanceAdditionalIpInput is an input type that accepts InstanceAdditionalIpArgs and InstanceAdditionalIpOutput values.
// You can construct a concrete instance of `InstanceAdditionalIpInput` via:
//
//	InstanceAdditionalIpArgs{...}
type InstanceAdditionalIpInput interface {
	pulumi.Input

	ToInstanceAdditionalIpOutput() InstanceAdditionalIpOutput
	ToInstanceAdditionalIpOutputWithContext(context.Context) InstanceAdditionalIpOutput
}

type InstanceAdditionalIpArgs struct {
	V4s InstanceAdditionalIpV4ArrayInput `pulumi:"v4s"`
}

func (InstanceAdditionalIpArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*InstanceAdditionalIp)(nil)).Elem()
}

func (i InstanceAdditionalIpArgs) ToInstanceAdditionalIpOutput() InstanceAdditionalIpOutput {
	return i.ToInstanceAdditionalIpOutputWithContext(context.Background())
}

func (i InstanceAdditionalIpArgs) ToInstanceAdditionalIpOutputWithContext(ctx context.Context) InstanceAdditionalIpOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceAdditionalIpOutput)
}

// InstanceAdditionalIpArrayInput is an input type that accepts InstanceAdditionalIpArray and InstanceAdditionalIpArrayOutput values.
// You can construct a concrete instance of `InstanceAdditionalIpArrayInput` via:
//
//	InstanceAdditionalIpArray{ InstanceAdditionalIpArgs{...} }
type InstanceAdditionalIpArrayInput interface {
	pulumi.Input

	ToInstanceAdditionalIpArrayOutput() InstanceAdditionalIpArrayOutput
	ToInstanceAdditionalIpArrayOutputWithContext(context.Context) InstanceAdditionalIpArrayOutput
}

type InstanceAdditionalIpArray []InstanceAdditionalIpInput

func (InstanceAdditionalIpArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]InstanceAdditionalIp)(nil)).Elem()
}

func (i InstanceAdditionalIpArray) ToInstanceAdditionalIpArrayOutput() InstanceAdditionalIpArrayOutput {
	return i.ToInstanceAdditionalIpArrayOutputWithContext(context.Background())
}

func (i InstanceAdditionalIpArray) ToInstanceAdditionalIpArrayOutputWithContext(ctx context.Context) InstanceAdditionalIpArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceAdditionalIpArrayOutput)
}

type InstanceAdditionalIpOutput struct{ *pulumi.OutputState }

func (InstanceAdditionalIpOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*InstanceAdditionalIp)(nil)).Elem()
}

func (o InstanceAdditionalIpOutput) ToInstanceAdditionalIpOutput() InstanceAdditionalIpOutput {
	return o
}

func (o InstanceAdditionalIpOutput) ToInstanceAdditionalIpOutputWithContext(ctx context.Context) InstanceAdditionalIpOutput {
	return o
}

func (o InstanceAdditionalIpOutput) V4s() InstanceAdditionalIpV4ArrayOutput {
	return o.ApplyT(func(v InstanceAdditionalIp) []InstanceAdditionalIpV4 { return v.V4s }).(InstanceAdditionalIpV4ArrayOutput)
}

type InstanceAdditionalIpArrayOutput struct{ *pulumi.OutputState }

func (InstanceAdditionalIpArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]InstanceAdditionalIp)(nil)).Elem()
}

func (o InstanceAdditionalIpArrayOutput) ToInstanceAdditionalIpArrayOutput() InstanceAdditionalIpArrayOutput {
	return o
}

func (o InstanceAdditionalIpArrayOutput) ToInstanceAdditionalIpArrayOutputWithContext(ctx context.Context) InstanceAdditionalIpArrayOutput {
	return o
}

func (o InstanceAdditionalIpArrayOutput) Index(i pulumi.IntInput) InstanceAdditionalIpOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) InstanceAdditionalIp {
		return vs[0].([]InstanceAdditionalIp)[vs[1].(int)]
	}).(InstanceAdditionalIpOutput)
}

type InstanceAdditionalIpV4 struct {
	Gateway     *string `pulumi:"gateway"`
	Ip          *string `pulumi:"ip"`
	NetmaskCidr *int    `pulumi:"netmaskCidr"`
}

// InstanceAdditionalIpV4Input is an input type that accepts InstanceAdditionalIpV4Args and InstanceAdditionalIpV4Output values.
// You can construct a concrete instance of `InstanceAdditionalIpV4Input` via:
//
//	InstanceAdditionalIpV4Args{...}
type InstanceAdditionalIpV4Input interface {
	pulumi.Input

	ToInstanceAdditionalIpV4Output() InstanceAdditionalIpV4Output
	ToInstanceAdditionalIpV4OutputWithContext(context.Context) InstanceAdditionalIpV4Output
}

type InstanceAdditionalIpV4Args struct {
	Gateway     pulumi.StringPtrInput `pulumi:"gateway"`
	Ip          pulumi.StringPtrInput `pulumi:"ip"`
	NetmaskCidr pulumi.IntPtrInput    `pulumi:"netmaskCidr"`
}

func (InstanceAdditionalIpV4Args) ElementType() reflect.Type {
	return reflect.TypeOf((*InstanceAdditionalIpV4)(nil)).Elem()
}

func (i InstanceAdditionalIpV4Args) ToInstanceAdditionalIpV4Output() InstanceAdditionalIpV4Output {
	return i.ToInstanceAdditionalIpV4OutputWithContext(context.Background())
}

func (i InstanceAdditionalIpV4Args) ToInstanceAdditionalIpV4OutputWithContext(ctx context.Context) InstanceAdditionalIpV4Output {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceAdditionalIpV4Output)
}

// InstanceAdditionalIpV4ArrayInput is an input type that accepts InstanceAdditionalIpV4Array and InstanceAdditionalIpV4ArrayOutput values.
// You can construct a concrete instance of `InstanceAdditionalIpV4ArrayInput` via:
//
//	InstanceAdditionalIpV4Array{ InstanceAdditionalIpV4Args{...} }
type InstanceAdditionalIpV4ArrayInput interface {
	pulumi.Input

	ToInstanceAdditionalIpV4ArrayOutput() InstanceAdditionalIpV4ArrayOutput
	ToInstanceAdditionalIpV4ArrayOutputWithContext(context.Context) InstanceAdditionalIpV4ArrayOutput
}

type InstanceAdditionalIpV4Array []InstanceAdditionalIpV4Input

func (InstanceAdditionalIpV4Array) ElementType() reflect.Type {
	return reflect.TypeOf((*[]InstanceAdditionalIpV4)(nil)).Elem()
}

func (i InstanceAdditionalIpV4Array) ToInstanceAdditionalIpV4ArrayOutput() InstanceAdditionalIpV4ArrayOutput {
	return i.ToInstanceAdditionalIpV4ArrayOutputWithContext(context.Background())
}

func (i InstanceAdditionalIpV4Array) ToInstanceAdditionalIpV4ArrayOutputWithContext(ctx context.Context) InstanceAdditionalIpV4ArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceAdditionalIpV4ArrayOutput)
}

type InstanceAdditionalIpV4Output struct{ *pulumi.OutputState }

func (InstanceAdditionalIpV4Output) ElementType() reflect.Type {
	return reflect.TypeOf((*InstanceAdditionalIpV4)(nil)).Elem()
}

func (o InstanceAdditionalIpV4Output) ToInstanceAdditionalIpV4Output() InstanceAdditionalIpV4Output {
	return o
}

func (o InstanceAdditionalIpV4Output) ToInstanceAdditionalIpV4OutputWithContext(ctx context.Context) InstanceAdditionalIpV4Output {
	return o
}

func (o InstanceAdditionalIpV4Output) Gateway() pulumi.StringPtrOutput {
	return o.ApplyT(func(v InstanceAdditionalIpV4) *string { return v.Gateway }).(pulumi.StringPtrOutput)
}

func (o InstanceAdditionalIpV4Output) Ip() pulumi.StringPtrOutput {
	return o.ApplyT(func(v InstanceAdditionalIpV4) *string { return v.Ip }).(pulumi.StringPtrOutput)
}

func (o InstanceAdditionalIpV4Output) NetmaskCidr() pulumi.IntPtrOutput {
	return o.ApplyT(func(v InstanceAdditionalIpV4) *int { return v.NetmaskCidr }).(pulumi.IntPtrOutput)
}

type InstanceAdditionalIpV4ArrayOutput struct{ *pulumi.OutputState }

func (InstanceAdditionalIpV4ArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]InstanceAdditionalIpV4)(nil)).Elem()
}

func (o InstanceAdditionalIpV4ArrayOutput) ToInstanceAdditionalIpV4ArrayOutput() InstanceAdditionalIpV4ArrayOutput {
	return o
}

func (o InstanceAdditionalIpV4ArrayOutput) ToInstanceAdditionalIpV4ArrayOutputWithContext(ctx context.Context) InstanceAdditionalIpV4ArrayOutput {
	return o
}

func (o InstanceAdditionalIpV4ArrayOutput) Index(i pulumi.IntInput) InstanceAdditionalIpV4Output {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) InstanceAdditionalIpV4 {
		return vs[0].([]InstanceAdditionalIpV4)[vs[1].(int)]
	}).(InstanceAdditionalIpV4Output)
}

type InstanceIpConfig struct {
	V4s []InstanceIpConfigV4 `pulumi:"v4s"`
	V6s []InstanceIpConfigV6 `pulumi:"v6s"`
}

// InstanceIpConfigInput is an input type that accepts InstanceIpConfigArgs and InstanceIpConfigOutput values.
// You can construct a concrete instance of `InstanceIpConfigInput` via:
//
//	InstanceIpConfigArgs{...}
type InstanceIpConfigInput interface {
	pulumi.Input

	ToInstanceIpConfigOutput() InstanceIpConfigOutput
	ToInstanceIpConfigOutputWithContext(context.Context) InstanceIpConfigOutput
}

type InstanceIpConfigArgs struct {
	V4s InstanceIpConfigV4ArrayInput `pulumi:"v4s"`
	V6s InstanceIpConfigV6ArrayInput `pulumi:"v6s"`
}

func (InstanceIpConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*InstanceIpConfig)(nil)).Elem()
}

func (i InstanceIpConfigArgs) ToInstanceIpConfigOutput() InstanceIpConfigOutput {
	return i.ToInstanceIpConfigOutputWithContext(context.Background())
}

func (i InstanceIpConfigArgs) ToInstanceIpConfigOutputWithContext(ctx context.Context) InstanceIpConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceIpConfigOutput)
}

// InstanceIpConfigArrayInput is an input type that accepts InstanceIpConfigArray and InstanceIpConfigArrayOutput values.
// You can construct a concrete instance of `InstanceIpConfigArrayInput` via:
//
//	InstanceIpConfigArray{ InstanceIpConfigArgs{...} }
type InstanceIpConfigArrayInput interface {
	pulumi.Input

	ToInstanceIpConfigArrayOutput() InstanceIpConfigArrayOutput
	ToInstanceIpConfigArrayOutputWithContext(context.Context) InstanceIpConfigArrayOutput
}

type InstanceIpConfigArray []InstanceIpConfigInput

func (InstanceIpConfigArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]InstanceIpConfig)(nil)).Elem()
}

func (i InstanceIpConfigArray) ToInstanceIpConfigArrayOutput() InstanceIpConfigArrayOutput {
	return i.ToInstanceIpConfigArrayOutputWithContext(context.Background())
}

func (i InstanceIpConfigArray) ToInstanceIpConfigArrayOutputWithContext(ctx context.Context) InstanceIpConfigArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceIpConfigArrayOutput)
}

type InstanceIpConfigOutput struct{ *pulumi.OutputState }

func (InstanceIpConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*InstanceIpConfig)(nil)).Elem()
}

func (o InstanceIpConfigOutput) ToInstanceIpConfigOutput() InstanceIpConfigOutput {
	return o
}

func (o InstanceIpConfigOutput) ToInstanceIpConfigOutputWithContext(ctx context.Context) InstanceIpConfigOutput {
	return o
}

func (o InstanceIpConfigOutput) V4s() InstanceIpConfigV4ArrayOutput {
	return o.ApplyT(func(v InstanceIpConfig) []InstanceIpConfigV4 { return v.V4s }).(InstanceIpConfigV4ArrayOutput)
}

func (o InstanceIpConfigOutput) V6s() InstanceIpConfigV6ArrayOutput {
	return o.ApplyT(func(v InstanceIpConfig) []InstanceIpConfigV6 { return v.V6s }).(InstanceIpConfigV6ArrayOutput)
}

type InstanceIpConfigArrayOutput struct{ *pulumi.OutputState }

func (InstanceIpConfigArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]InstanceIpConfig)(nil)).Elem()
}

func (o InstanceIpConfigArrayOutput) ToInstanceIpConfigArrayOutput() InstanceIpConfigArrayOutput {
	return o
}

func (o InstanceIpConfigArrayOutput) ToInstanceIpConfigArrayOutputWithContext(ctx context.Context) InstanceIpConfigArrayOutput {
	return o
}

func (o InstanceIpConfigArrayOutput) Index(i pulumi.IntInput) InstanceIpConfigOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) InstanceIpConfig {
		return vs[0].([]InstanceIpConfig)[vs[1].(int)]
	}).(InstanceIpConfigOutput)
}

type InstanceIpConfigV4 struct {
	Gateway     *string `pulumi:"gateway"`
	Ip          *string `pulumi:"ip"`
	NetmaskCidr *int    `pulumi:"netmaskCidr"`
}

// InstanceIpConfigV4Input is an input type that accepts InstanceIpConfigV4Args and InstanceIpConfigV4Output values.
// You can construct a concrete instance of `InstanceIpConfigV4Input` via:
//
//	InstanceIpConfigV4Args{...}
type InstanceIpConfigV4Input interface {
	pulumi.Input

	ToInstanceIpConfigV4Output() InstanceIpConfigV4Output
	ToInstanceIpConfigV4OutputWithContext(context.Context) InstanceIpConfigV4Output
}

type InstanceIpConfigV4Args struct {
	Gateway     pulumi.StringPtrInput `pulumi:"gateway"`
	Ip          pulumi.StringPtrInput `pulumi:"ip"`
	NetmaskCidr pulumi.IntPtrInput    `pulumi:"netmaskCidr"`
}

func (InstanceIpConfigV4Args) ElementType() reflect.Type {
	return reflect.TypeOf((*InstanceIpConfigV4)(nil)).Elem()
}

func (i InstanceIpConfigV4Args) ToInstanceIpConfigV4Output() InstanceIpConfigV4Output {
	return i.ToInstanceIpConfigV4OutputWithContext(context.Background())
}

func (i InstanceIpConfigV4Args) ToInstanceIpConfigV4OutputWithContext(ctx context.Context) InstanceIpConfigV4Output {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceIpConfigV4Output)
}

// InstanceIpConfigV4ArrayInput is an input type that accepts InstanceIpConfigV4Array and InstanceIpConfigV4ArrayOutput values.
// You can construct a concrete instance of `InstanceIpConfigV4ArrayInput` via:
//
//	InstanceIpConfigV4Array{ InstanceIpConfigV4Args{...} }
type InstanceIpConfigV4ArrayInput interface {
	pulumi.Input

	ToInstanceIpConfigV4ArrayOutput() InstanceIpConfigV4ArrayOutput
	ToInstanceIpConfigV4ArrayOutputWithContext(context.Context) InstanceIpConfigV4ArrayOutput
}

type InstanceIpConfigV4Array []InstanceIpConfigV4Input

func (InstanceIpConfigV4Array) ElementType() reflect.Type {
	return reflect.TypeOf((*[]InstanceIpConfigV4)(nil)).Elem()
}

func (i InstanceIpConfigV4Array) ToInstanceIpConfigV4ArrayOutput() InstanceIpConfigV4ArrayOutput {
	return i.ToInstanceIpConfigV4ArrayOutputWithContext(context.Background())
}

func (i InstanceIpConfigV4Array) ToInstanceIpConfigV4ArrayOutputWithContext(ctx context.Context) InstanceIpConfigV4ArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceIpConfigV4ArrayOutput)
}

type InstanceIpConfigV4Output struct{ *pulumi.OutputState }

func (InstanceIpConfigV4Output) ElementType() reflect.Type {
	return reflect.TypeOf((*InstanceIpConfigV4)(nil)).Elem()
}

func (o InstanceIpConfigV4Output) ToInstanceIpConfigV4Output() InstanceIpConfigV4Output {
	return o
}

func (o InstanceIpConfigV4Output) ToInstanceIpConfigV4OutputWithContext(ctx context.Context) InstanceIpConfigV4Output {
	return o
}

func (o InstanceIpConfigV4Output) Gateway() pulumi.StringPtrOutput {
	return o.ApplyT(func(v InstanceIpConfigV4) *string { return v.Gateway }).(pulumi.StringPtrOutput)
}

func (o InstanceIpConfigV4Output) Ip() pulumi.StringPtrOutput {
	return o.ApplyT(func(v InstanceIpConfigV4) *string { return v.Ip }).(pulumi.StringPtrOutput)
}

func (o InstanceIpConfigV4Output) NetmaskCidr() pulumi.IntPtrOutput {
	return o.ApplyT(func(v InstanceIpConfigV4) *int { return v.NetmaskCidr }).(pulumi.IntPtrOutput)
}

type InstanceIpConfigV4ArrayOutput struct{ *pulumi.OutputState }

func (InstanceIpConfigV4ArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]InstanceIpConfigV4)(nil)).Elem()
}

func (o InstanceIpConfigV4ArrayOutput) ToInstanceIpConfigV4ArrayOutput() InstanceIpConfigV4ArrayOutput {
	return o
}

func (o InstanceIpConfigV4ArrayOutput) ToInstanceIpConfigV4ArrayOutputWithContext(ctx context.Context) InstanceIpConfigV4ArrayOutput {
	return o
}

func (o InstanceIpConfigV4ArrayOutput) Index(i pulumi.IntInput) InstanceIpConfigV4Output {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) InstanceIpConfigV4 {
		return vs[0].([]InstanceIpConfigV4)[vs[1].(int)]
	}).(InstanceIpConfigV4Output)
}

type InstanceIpConfigV6 struct {
	Gateway     *string `pulumi:"gateway"`
	Ip          *string `pulumi:"ip"`
	NetmaskCidr *int    `pulumi:"netmaskCidr"`
}

// InstanceIpConfigV6Input is an input type that accepts InstanceIpConfigV6Args and InstanceIpConfigV6Output values.
// You can construct a concrete instance of `InstanceIpConfigV6Input` via:
//
//	InstanceIpConfigV6Args{...}
type InstanceIpConfigV6Input interface {
	pulumi.Input

	ToInstanceIpConfigV6Output() InstanceIpConfigV6Output
	ToInstanceIpConfigV6OutputWithContext(context.Context) InstanceIpConfigV6Output
}

type InstanceIpConfigV6Args struct {
	Gateway     pulumi.StringPtrInput `pulumi:"gateway"`
	Ip          pulumi.StringPtrInput `pulumi:"ip"`
	NetmaskCidr pulumi.IntPtrInput    `pulumi:"netmaskCidr"`
}

func (InstanceIpConfigV6Args) ElementType() reflect.Type {
	return reflect.TypeOf((*InstanceIpConfigV6)(nil)).Elem()
}

func (i InstanceIpConfigV6Args) ToInstanceIpConfigV6Output() InstanceIpConfigV6Output {
	return i.ToInstanceIpConfigV6OutputWithContext(context.Background())
}

func (i InstanceIpConfigV6Args) ToInstanceIpConfigV6OutputWithContext(ctx context.Context) InstanceIpConfigV6Output {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceIpConfigV6Output)
}

// InstanceIpConfigV6ArrayInput is an input type that accepts InstanceIpConfigV6Array and InstanceIpConfigV6ArrayOutput values.
// You can construct a concrete instance of `InstanceIpConfigV6ArrayInput` via:
//
//	InstanceIpConfigV6Array{ InstanceIpConfigV6Args{...} }
type InstanceIpConfigV6ArrayInput interface {
	pulumi.Input

	ToInstanceIpConfigV6ArrayOutput() InstanceIpConfigV6ArrayOutput
	ToInstanceIpConfigV6ArrayOutputWithContext(context.Context) InstanceIpConfigV6ArrayOutput
}

type InstanceIpConfigV6Array []InstanceIpConfigV6Input

func (InstanceIpConfigV6Array) ElementType() reflect.Type {
	return reflect.TypeOf((*[]InstanceIpConfigV6)(nil)).Elem()
}

func (i InstanceIpConfigV6Array) ToInstanceIpConfigV6ArrayOutput() InstanceIpConfigV6ArrayOutput {
	return i.ToInstanceIpConfigV6ArrayOutputWithContext(context.Background())
}

func (i InstanceIpConfigV6Array) ToInstanceIpConfigV6ArrayOutputWithContext(ctx context.Context) InstanceIpConfigV6ArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceIpConfigV6ArrayOutput)
}

type InstanceIpConfigV6Output struct{ *pulumi.OutputState }

func (InstanceIpConfigV6Output) ElementType() reflect.Type {
	return reflect.TypeOf((*InstanceIpConfigV6)(nil)).Elem()
}

func (o InstanceIpConfigV6Output) ToInstanceIpConfigV6Output() InstanceIpConfigV6Output {
	return o
}

func (o InstanceIpConfigV6Output) ToInstanceIpConfigV6OutputWithContext(ctx context.Context) InstanceIpConfigV6Output {
	return o
}

func (o InstanceIpConfigV6Output) Gateway() pulumi.StringPtrOutput {
	return o.ApplyT(func(v InstanceIpConfigV6) *string { return v.Gateway }).(pulumi.StringPtrOutput)
}

func (o InstanceIpConfigV6Output) Ip() pulumi.StringPtrOutput {
	return o.ApplyT(func(v InstanceIpConfigV6) *string { return v.Ip }).(pulumi.StringPtrOutput)
}

func (o InstanceIpConfigV6Output) NetmaskCidr() pulumi.IntPtrOutput {
	return o.ApplyT(func(v InstanceIpConfigV6) *int { return v.NetmaskCidr }).(pulumi.IntPtrOutput)
}

type InstanceIpConfigV6ArrayOutput struct{ *pulumi.OutputState }

func (InstanceIpConfigV6ArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]InstanceIpConfigV6)(nil)).Elem()
}

func (o InstanceIpConfigV6ArrayOutput) ToInstanceIpConfigV6ArrayOutput() InstanceIpConfigV6ArrayOutput {
	return o
}

func (o InstanceIpConfigV6ArrayOutput) ToInstanceIpConfigV6ArrayOutputWithContext(ctx context.Context) InstanceIpConfigV6ArrayOutput {
	return o
}

func (o InstanceIpConfigV6ArrayOutput) Index(i pulumi.IntInput) InstanceIpConfigV6Output {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) InstanceIpConfigV6 {
		return vs[0].([]InstanceIpConfigV6)[vs[1].(int)]
	}).(InstanceIpConfigV6Output)
}

type Object_storageAutoScaling struct {
	ErrorMessage *string  `pulumi:"errorMessage"`
	SizeLimitTb  *float64 `pulumi:"sizeLimitTb"`
	State        *string  `pulumi:"state"`
}

// Object_storageAutoScalingInput is an input type that accepts Object_storageAutoScalingArgs and Object_storageAutoScalingOutput values.
// You can construct a concrete instance of `Object_storageAutoScalingInput` via:
//
//	Object_storageAutoScalingArgs{...}
type Object_storageAutoScalingInput interface {
	pulumi.Input

	ToObject_storageAutoScalingOutput() Object_storageAutoScalingOutput
	ToObject_storageAutoScalingOutputWithContext(context.Context) Object_storageAutoScalingOutput
}

type Object_storageAutoScalingArgs struct {
	ErrorMessage pulumi.StringPtrInput  `pulumi:"errorMessage"`
	SizeLimitTb  pulumi.Float64PtrInput `pulumi:"sizeLimitTb"`
	State        pulumi.StringPtrInput  `pulumi:"state"`
}

func (Object_storageAutoScalingArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Object_storageAutoScaling)(nil)).Elem()
}

func (i Object_storageAutoScalingArgs) ToObject_storageAutoScalingOutput() Object_storageAutoScalingOutput {
	return i.ToObject_storageAutoScalingOutputWithContext(context.Background())
}

func (i Object_storageAutoScalingArgs) ToObject_storageAutoScalingOutputWithContext(ctx context.Context) Object_storageAutoScalingOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Object_storageAutoScalingOutput)
}

// Object_storageAutoScalingArrayInput is an input type that accepts Object_storageAutoScalingArray and Object_storageAutoScalingArrayOutput values.
// You can construct a concrete instance of `Object_storageAutoScalingArrayInput` via:
//
//	Object_storageAutoScalingArray{ Object_storageAutoScalingArgs{...} }
type Object_storageAutoScalingArrayInput interface {
	pulumi.Input

	ToObject_storageAutoScalingArrayOutput() Object_storageAutoScalingArrayOutput
	ToObject_storageAutoScalingArrayOutputWithContext(context.Context) Object_storageAutoScalingArrayOutput
}

type Object_storageAutoScalingArray []Object_storageAutoScalingInput

func (Object_storageAutoScalingArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Object_storageAutoScaling)(nil)).Elem()
}

func (i Object_storageAutoScalingArray) ToObject_storageAutoScalingArrayOutput() Object_storageAutoScalingArrayOutput {
	return i.ToObject_storageAutoScalingArrayOutputWithContext(context.Background())
}

func (i Object_storageAutoScalingArray) ToObject_storageAutoScalingArrayOutputWithContext(ctx context.Context) Object_storageAutoScalingArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Object_storageAutoScalingArrayOutput)
}

type Object_storageAutoScalingOutput struct{ *pulumi.OutputState }

func (Object_storageAutoScalingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Object_storageAutoScaling)(nil)).Elem()
}

func (o Object_storageAutoScalingOutput) ToObject_storageAutoScalingOutput() Object_storageAutoScalingOutput {
	return o
}

func (o Object_storageAutoScalingOutput) ToObject_storageAutoScalingOutputWithContext(ctx context.Context) Object_storageAutoScalingOutput {
	return o
}

func (o Object_storageAutoScalingOutput) ErrorMessage() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Object_storageAutoScaling) *string { return v.ErrorMessage }).(pulumi.StringPtrOutput)
}

func (o Object_storageAutoScalingOutput) SizeLimitTb() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v Object_storageAutoScaling) *float64 { return v.SizeLimitTb }).(pulumi.Float64PtrOutput)
}

func (o Object_storageAutoScalingOutput) State() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Object_storageAutoScaling) *string { return v.State }).(pulumi.StringPtrOutput)
}

type Object_storageAutoScalingArrayOutput struct{ *pulumi.OutputState }

func (Object_storageAutoScalingArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Object_storageAutoScaling)(nil)).Elem()
}

func (o Object_storageAutoScalingArrayOutput) ToObject_storageAutoScalingArrayOutput() Object_storageAutoScalingArrayOutput {
	return o
}

func (o Object_storageAutoScalingArrayOutput) ToObject_storageAutoScalingArrayOutputWithContext(ctx context.Context) Object_storageAutoScalingArrayOutput {
	return o
}

func (o Object_storageAutoScalingArrayOutput) Index(i pulumi.IntInput) Object_storageAutoScalingOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) Object_storageAutoScaling {
		return vs[0].([]Object_storageAutoScaling)[vs[1].(int)]
	}).(Object_storageAutoScalingOutput)
}

type Private_networkInstance struct {
	DisplayName      *string                                  `pulumi:"displayName"`
	ErrorMessage     *string                                  `pulumi:"errorMessage"`
	InstanceId       *int                                     `pulumi:"instanceId"`
	Name             *string                                  `pulumi:"name"`
	PrivateIpConfigs []Private_networkInstancePrivateIpConfig `pulumi:"privateIpConfigs"`
	Status           *string                                  `pulumi:"status"`
}

// Private_networkInstanceInput is an input type that accepts Private_networkInstanceArgs and Private_networkInstanceOutput values.
// You can construct a concrete instance of `Private_networkInstanceInput` via:
//
//	Private_networkInstanceArgs{...}
type Private_networkInstanceInput interface {
	pulumi.Input

	ToPrivate_networkInstanceOutput() Private_networkInstanceOutput
	ToPrivate_networkInstanceOutputWithContext(context.Context) Private_networkInstanceOutput
}

type Private_networkInstanceArgs struct {
	DisplayName      pulumi.StringPtrInput                            `pulumi:"displayName"`
	ErrorMessage     pulumi.StringPtrInput                            `pulumi:"errorMessage"`
	InstanceId       pulumi.IntPtrInput                               `pulumi:"instanceId"`
	Name             pulumi.StringPtrInput                            `pulumi:"name"`
	PrivateIpConfigs Private_networkInstancePrivateIpConfigArrayInput `pulumi:"privateIpConfigs"`
	Status           pulumi.StringPtrInput                            `pulumi:"status"`
}

func (Private_networkInstanceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Private_networkInstance)(nil)).Elem()
}

func (i Private_networkInstanceArgs) ToPrivate_networkInstanceOutput() Private_networkInstanceOutput {
	return i.ToPrivate_networkInstanceOutputWithContext(context.Background())
}

func (i Private_networkInstanceArgs) ToPrivate_networkInstanceOutputWithContext(ctx context.Context) Private_networkInstanceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Private_networkInstanceOutput)
}

// Private_networkInstanceArrayInput is an input type that accepts Private_networkInstanceArray and Private_networkInstanceArrayOutput values.
// You can construct a concrete instance of `Private_networkInstanceArrayInput` via:
//
//	Private_networkInstanceArray{ Private_networkInstanceArgs{...} }
type Private_networkInstanceArrayInput interface {
	pulumi.Input

	ToPrivate_networkInstanceArrayOutput() Private_networkInstanceArrayOutput
	ToPrivate_networkInstanceArrayOutputWithContext(context.Context) Private_networkInstanceArrayOutput
}

type Private_networkInstanceArray []Private_networkInstanceInput

func (Private_networkInstanceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Private_networkInstance)(nil)).Elem()
}

func (i Private_networkInstanceArray) ToPrivate_networkInstanceArrayOutput() Private_networkInstanceArrayOutput {
	return i.ToPrivate_networkInstanceArrayOutputWithContext(context.Background())
}

func (i Private_networkInstanceArray) ToPrivate_networkInstanceArrayOutputWithContext(ctx context.Context) Private_networkInstanceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Private_networkInstanceArrayOutput)
}

type Private_networkInstanceOutput struct{ *pulumi.OutputState }

func (Private_networkInstanceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Private_networkInstance)(nil)).Elem()
}

func (o Private_networkInstanceOutput) ToPrivate_networkInstanceOutput() Private_networkInstanceOutput {
	return o
}

func (o Private_networkInstanceOutput) ToPrivate_networkInstanceOutputWithContext(ctx context.Context) Private_networkInstanceOutput {
	return o
}

func (o Private_networkInstanceOutput) DisplayName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Private_networkInstance) *string { return v.DisplayName }).(pulumi.StringPtrOutput)
}

func (o Private_networkInstanceOutput) ErrorMessage() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Private_networkInstance) *string { return v.ErrorMessage }).(pulumi.StringPtrOutput)
}

func (o Private_networkInstanceOutput) InstanceId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Private_networkInstance) *int { return v.InstanceId }).(pulumi.IntPtrOutput)
}

func (o Private_networkInstanceOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Private_networkInstance) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o Private_networkInstanceOutput) PrivateIpConfigs() Private_networkInstancePrivateIpConfigArrayOutput {
	return o.ApplyT(func(v Private_networkInstance) []Private_networkInstancePrivateIpConfig { return v.PrivateIpConfigs }).(Private_networkInstancePrivateIpConfigArrayOutput)
}

func (o Private_networkInstanceOutput) Status() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Private_networkInstance) *string { return v.Status }).(pulumi.StringPtrOutput)
}

type Private_networkInstanceArrayOutput struct{ *pulumi.OutputState }

func (Private_networkInstanceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Private_networkInstance)(nil)).Elem()
}

func (o Private_networkInstanceArrayOutput) ToPrivate_networkInstanceArrayOutput() Private_networkInstanceArrayOutput {
	return o
}

func (o Private_networkInstanceArrayOutput) ToPrivate_networkInstanceArrayOutputWithContext(ctx context.Context) Private_networkInstanceArrayOutput {
	return o
}

func (o Private_networkInstanceArrayOutput) Index(i pulumi.IntInput) Private_networkInstanceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) Private_networkInstance {
		return vs[0].([]Private_networkInstance)[vs[1].(int)]
	}).(Private_networkInstanceOutput)
}

type Private_networkInstancePrivateIpConfig struct {
	V4s []Private_networkInstancePrivateIpConfigV4 `pulumi:"v4s"`
}

// Private_networkInstancePrivateIpConfigInput is an input type that accepts Private_networkInstancePrivateIpConfigArgs and Private_networkInstancePrivateIpConfigOutput values.
// You can construct a concrete instance of `Private_networkInstancePrivateIpConfigInput` via:
//
//	Private_networkInstancePrivateIpConfigArgs{...}
type Private_networkInstancePrivateIpConfigInput interface {
	pulumi.Input

	ToPrivate_networkInstancePrivateIpConfigOutput() Private_networkInstancePrivateIpConfigOutput
	ToPrivate_networkInstancePrivateIpConfigOutputWithContext(context.Context) Private_networkInstancePrivateIpConfigOutput
}

type Private_networkInstancePrivateIpConfigArgs struct {
	V4s Private_networkInstancePrivateIpConfigV4ArrayInput `pulumi:"v4s"`
}

func (Private_networkInstancePrivateIpConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Private_networkInstancePrivateIpConfig)(nil)).Elem()
}

func (i Private_networkInstancePrivateIpConfigArgs) ToPrivate_networkInstancePrivateIpConfigOutput() Private_networkInstancePrivateIpConfigOutput {
	return i.ToPrivate_networkInstancePrivateIpConfigOutputWithContext(context.Background())
}

func (i Private_networkInstancePrivateIpConfigArgs) ToPrivate_networkInstancePrivateIpConfigOutputWithContext(ctx context.Context) Private_networkInstancePrivateIpConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Private_networkInstancePrivateIpConfigOutput)
}

// Private_networkInstancePrivateIpConfigArrayInput is an input type that accepts Private_networkInstancePrivateIpConfigArray and Private_networkInstancePrivateIpConfigArrayOutput values.
// You can construct a concrete instance of `Private_networkInstancePrivateIpConfigArrayInput` via:
//
//	Private_networkInstancePrivateIpConfigArray{ Private_networkInstancePrivateIpConfigArgs{...} }
type Private_networkInstancePrivateIpConfigArrayInput interface {
	pulumi.Input

	ToPrivate_networkInstancePrivateIpConfigArrayOutput() Private_networkInstancePrivateIpConfigArrayOutput
	ToPrivate_networkInstancePrivateIpConfigArrayOutputWithContext(context.Context) Private_networkInstancePrivateIpConfigArrayOutput
}

type Private_networkInstancePrivateIpConfigArray []Private_networkInstancePrivateIpConfigInput

func (Private_networkInstancePrivateIpConfigArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Private_networkInstancePrivateIpConfig)(nil)).Elem()
}

func (i Private_networkInstancePrivateIpConfigArray) ToPrivate_networkInstancePrivateIpConfigArrayOutput() Private_networkInstancePrivateIpConfigArrayOutput {
	return i.ToPrivate_networkInstancePrivateIpConfigArrayOutputWithContext(context.Background())
}

func (i Private_networkInstancePrivateIpConfigArray) ToPrivate_networkInstancePrivateIpConfigArrayOutputWithContext(ctx context.Context) Private_networkInstancePrivateIpConfigArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Private_networkInstancePrivateIpConfigArrayOutput)
}

type Private_networkInstancePrivateIpConfigOutput struct{ *pulumi.OutputState }

func (Private_networkInstancePrivateIpConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Private_networkInstancePrivateIpConfig)(nil)).Elem()
}

func (o Private_networkInstancePrivateIpConfigOutput) ToPrivate_networkInstancePrivateIpConfigOutput() Private_networkInstancePrivateIpConfigOutput {
	return o
}

func (o Private_networkInstancePrivateIpConfigOutput) ToPrivate_networkInstancePrivateIpConfigOutputWithContext(ctx context.Context) Private_networkInstancePrivateIpConfigOutput {
	return o
}

func (o Private_networkInstancePrivateIpConfigOutput) V4s() Private_networkInstancePrivateIpConfigV4ArrayOutput {
	return o.ApplyT(func(v Private_networkInstancePrivateIpConfig) []Private_networkInstancePrivateIpConfigV4 {
		return v.V4s
	}).(Private_networkInstancePrivateIpConfigV4ArrayOutput)
}

type Private_networkInstancePrivateIpConfigArrayOutput struct{ *pulumi.OutputState }

func (Private_networkInstancePrivateIpConfigArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Private_networkInstancePrivateIpConfig)(nil)).Elem()
}

func (o Private_networkInstancePrivateIpConfigArrayOutput) ToPrivate_networkInstancePrivateIpConfigArrayOutput() Private_networkInstancePrivateIpConfigArrayOutput {
	return o
}

func (o Private_networkInstancePrivateIpConfigArrayOutput) ToPrivate_networkInstancePrivateIpConfigArrayOutputWithContext(ctx context.Context) Private_networkInstancePrivateIpConfigArrayOutput {
	return o
}

func (o Private_networkInstancePrivateIpConfigArrayOutput) Index(i pulumi.IntInput) Private_networkInstancePrivateIpConfigOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) Private_networkInstancePrivateIpConfig {
		return vs[0].([]Private_networkInstancePrivateIpConfig)[vs[1].(int)]
	}).(Private_networkInstancePrivateIpConfigOutput)
}

type Private_networkInstancePrivateIpConfigV4 struct {
	Gateway     *string `pulumi:"gateway"`
	Ip          *string `pulumi:"ip"`
	NetmaskCidr *int    `pulumi:"netmaskCidr"`
}

// Private_networkInstancePrivateIpConfigV4Input is an input type that accepts Private_networkInstancePrivateIpConfigV4Args and Private_networkInstancePrivateIpConfigV4Output values.
// You can construct a concrete instance of `Private_networkInstancePrivateIpConfigV4Input` via:
//
//	Private_networkInstancePrivateIpConfigV4Args{...}
type Private_networkInstancePrivateIpConfigV4Input interface {
	pulumi.Input

	ToPrivate_networkInstancePrivateIpConfigV4Output() Private_networkInstancePrivateIpConfigV4Output
	ToPrivate_networkInstancePrivateIpConfigV4OutputWithContext(context.Context) Private_networkInstancePrivateIpConfigV4Output
}

type Private_networkInstancePrivateIpConfigV4Args struct {
	Gateway     pulumi.StringPtrInput `pulumi:"gateway"`
	Ip          pulumi.StringPtrInput `pulumi:"ip"`
	NetmaskCidr pulumi.IntPtrInput    `pulumi:"netmaskCidr"`
}

func (Private_networkInstancePrivateIpConfigV4Args) ElementType() reflect.Type {
	return reflect.TypeOf((*Private_networkInstancePrivateIpConfigV4)(nil)).Elem()
}

func (i Private_networkInstancePrivateIpConfigV4Args) ToPrivate_networkInstancePrivateIpConfigV4Output() Private_networkInstancePrivateIpConfigV4Output {
	return i.ToPrivate_networkInstancePrivateIpConfigV4OutputWithContext(context.Background())
}

func (i Private_networkInstancePrivateIpConfigV4Args) ToPrivate_networkInstancePrivateIpConfigV4OutputWithContext(ctx context.Context) Private_networkInstancePrivateIpConfigV4Output {
	return pulumi.ToOutputWithContext(ctx, i).(Private_networkInstancePrivateIpConfigV4Output)
}

// Private_networkInstancePrivateIpConfigV4ArrayInput is an input type that accepts Private_networkInstancePrivateIpConfigV4Array and Private_networkInstancePrivateIpConfigV4ArrayOutput values.
// You can construct a concrete instance of `Private_networkInstancePrivateIpConfigV4ArrayInput` via:
//
//	Private_networkInstancePrivateIpConfigV4Array{ Private_networkInstancePrivateIpConfigV4Args{...} }
type Private_networkInstancePrivateIpConfigV4ArrayInput interface {
	pulumi.Input

	ToPrivate_networkInstancePrivateIpConfigV4ArrayOutput() Private_networkInstancePrivateIpConfigV4ArrayOutput
	ToPrivate_networkInstancePrivateIpConfigV4ArrayOutputWithContext(context.Context) Private_networkInstancePrivateIpConfigV4ArrayOutput
}

type Private_networkInstancePrivateIpConfigV4Array []Private_networkInstancePrivateIpConfigV4Input

func (Private_networkInstancePrivateIpConfigV4Array) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Private_networkInstancePrivateIpConfigV4)(nil)).Elem()
}

func (i Private_networkInstancePrivateIpConfigV4Array) ToPrivate_networkInstancePrivateIpConfigV4ArrayOutput() Private_networkInstancePrivateIpConfigV4ArrayOutput {
	return i.ToPrivate_networkInstancePrivateIpConfigV4ArrayOutputWithContext(context.Background())
}

func (i Private_networkInstancePrivateIpConfigV4Array) ToPrivate_networkInstancePrivateIpConfigV4ArrayOutputWithContext(ctx context.Context) Private_networkInstancePrivateIpConfigV4ArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Private_networkInstancePrivateIpConfigV4ArrayOutput)
}

type Private_networkInstancePrivateIpConfigV4Output struct{ *pulumi.OutputState }

func (Private_networkInstancePrivateIpConfigV4Output) ElementType() reflect.Type {
	return reflect.TypeOf((*Private_networkInstancePrivateIpConfigV4)(nil)).Elem()
}

func (o Private_networkInstancePrivateIpConfigV4Output) ToPrivate_networkInstancePrivateIpConfigV4Output() Private_networkInstancePrivateIpConfigV4Output {
	return o
}

func (o Private_networkInstancePrivateIpConfigV4Output) ToPrivate_networkInstancePrivateIpConfigV4OutputWithContext(ctx context.Context) Private_networkInstancePrivateIpConfigV4Output {
	return o
}

func (o Private_networkInstancePrivateIpConfigV4Output) Gateway() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Private_networkInstancePrivateIpConfigV4) *string { return v.Gateway }).(pulumi.StringPtrOutput)
}

func (o Private_networkInstancePrivateIpConfigV4Output) Ip() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Private_networkInstancePrivateIpConfigV4) *string { return v.Ip }).(pulumi.StringPtrOutput)
}

func (o Private_networkInstancePrivateIpConfigV4Output) NetmaskCidr() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Private_networkInstancePrivateIpConfigV4) *int { return v.NetmaskCidr }).(pulumi.IntPtrOutput)
}

type Private_networkInstancePrivateIpConfigV4ArrayOutput struct{ *pulumi.OutputState }

func (Private_networkInstancePrivateIpConfigV4ArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Private_networkInstancePrivateIpConfigV4)(nil)).Elem()
}

func (o Private_networkInstancePrivateIpConfigV4ArrayOutput) ToPrivate_networkInstancePrivateIpConfigV4ArrayOutput() Private_networkInstancePrivateIpConfigV4ArrayOutput {
	return o
}

func (o Private_networkInstancePrivateIpConfigV4ArrayOutput) ToPrivate_networkInstancePrivateIpConfigV4ArrayOutputWithContext(ctx context.Context) Private_networkInstancePrivateIpConfigV4ArrayOutput {
	return o
}

func (o Private_networkInstancePrivateIpConfigV4ArrayOutput) Index(i pulumi.IntInput) Private_networkInstancePrivateIpConfigV4Output {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) Private_networkInstancePrivateIpConfigV4 {
		return vs[0].([]Private_networkInstancePrivateIpConfigV4)[vs[1].(int)]
	}).(Private_networkInstancePrivateIpConfigV4Output)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GetInstanceAddOnInput)(nil)).Elem(), GetInstanceAddOnArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetInstanceAddOnArrayInput)(nil)).Elem(), GetInstanceAddOnArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetInstanceAdditionalIpsV4Input)(nil)).Elem(), GetInstanceAdditionalIpsV4Args{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetInstanceAdditionalIpsV4ArrayInput)(nil)).Elem(), GetInstanceAdditionalIpsV4Array{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetInstanceIpConfigInput)(nil)).Elem(), GetInstanceIpConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetInstanceIpConfigArrayInput)(nil)).Elem(), GetInstanceIpConfigArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetInstanceIpConfigV4Input)(nil)).Elem(), GetInstanceIpConfigV4Args{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetInstanceIpConfigV4ArrayInput)(nil)).Elem(), GetInstanceIpConfigV4Array{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetInstanceIpConfigV6Input)(nil)).Elem(), GetInstanceIpConfigV6Args{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetInstanceIpConfigV6ArrayInput)(nil)).Elem(), GetInstanceIpConfigV6Array{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetObjectStorageAutoScalingInput)(nil)).Elem(), GetObjectStorageAutoScalingArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetObjectStorageAutoScalingArrayInput)(nil)).Elem(), GetObjectStorageAutoScalingArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPrivateNetworkInstanceInput)(nil)).Elem(), GetPrivateNetworkInstanceArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPrivateNetworkInstanceArrayInput)(nil)).Elem(), GetPrivateNetworkInstanceArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPrivateNetworkInstancePrivateIpConfigInput)(nil)).Elem(), GetPrivateNetworkInstancePrivateIpConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPrivateNetworkInstancePrivateIpConfigArrayInput)(nil)).Elem(), GetPrivateNetworkInstancePrivateIpConfigArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPrivateNetworkInstancePrivateIpConfigV4Input)(nil)).Elem(), GetPrivateNetworkInstancePrivateIpConfigV4Args{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPrivateNetworkInstancePrivateIpConfigV4ArrayInput)(nil)).Elem(), GetPrivateNetworkInstancePrivateIpConfigV4Array{})
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceAddOnInput)(nil)).Elem(), InstanceAddOnArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceAddOnArrayInput)(nil)).Elem(), InstanceAddOnArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceAdditionalIpInput)(nil)).Elem(), InstanceAdditionalIpArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceAdditionalIpArrayInput)(nil)).Elem(), InstanceAdditionalIpArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceAdditionalIpV4Input)(nil)).Elem(), InstanceAdditionalIpV4Args{})
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceAdditionalIpV4ArrayInput)(nil)).Elem(), InstanceAdditionalIpV4Array{})
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceIpConfigInput)(nil)).Elem(), InstanceIpConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceIpConfigArrayInput)(nil)).Elem(), InstanceIpConfigArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceIpConfigV4Input)(nil)).Elem(), InstanceIpConfigV4Args{})
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceIpConfigV4ArrayInput)(nil)).Elem(), InstanceIpConfigV4Array{})
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceIpConfigV6Input)(nil)).Elem(), InstanceIpConfigV6Args{})
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceIpConfigV6ArrayInput)(nil)).Elem(), InstanceIpConfigV6Array{})
	pulumi.RegisterInputType(reflect.TypeOf((*Object_storageAutoScalingInput)(nil)).Elem(), Object_storageAutoScalingArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*Object_storageAutoScalingArrayInput)(nil)).Elem(), Object_storageAutoScalingArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*Private_networkInstanceInput)(nil)).Elem(), Private_networkInstanceArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*Private_networkInstanceArrayInput)(nil)).Elem(), Private_networkInstanceArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*Private_networkInstancePrivateIpConfigInput)(nil)).Elem(), Private_networkInstancePrivateIpConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*Private_networkInstancePrivateIpConfigArrayInput)(nil)).Elem(), Private_networkInstancePrivateIpConfigArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*Private_networkInstancePrivateIpConfigV4Input)(nil)).Elem(), Private_networkInstancePrivateIpConfigV4Args{})
	pulumi.RegisterInputType(reflect.TypeOf((*Private_networkInstancePrivateIpConfigV4ArrayInput)(nil)).Elem(), Private_networkInstancePrivateIpConfigV4Array{})
	pulumi.RegisterOutputType(GetInstanceAddOnOutput{})
	pulumi.RegisterOutputType(GetInstanceAddOnArrayOutput{})
	pulumi.RegisterOutputType(GetInstanceAdditionalIpsV4Output{})
	pulumi.RegisterOutputType(GetInstanceAdditionalIpsV4ArrayOutput{})
	pulumi.RegisterOutputType(GetInstanceIpConfigOutput{})
	pulumi.RegisterOutputType(GetInstanceIpConfigArrayOutput{})
	pulumi.RegisterOutputType(GetInstanceIpConfigV4Output{})
	pulumi.RegisterOutputType(GetInstanceIpConfigV4ArrayOutput{})
	pulumi.RegisterOutputType(GetInstanceIpConfigV6Output{})
	pulumi.RegisterOutputType(GetInstanceIpConfigV6ArrayOutput{})
	pulumi.RegisterOutputType(GetObjectStorageAutoScalingOutput{})
	pulumi.RegisterOutputType(GetObjectStorageAutoScalingArrayOutput{})
	pulumi.RegisterOutputType(GetPrivateNetworkInstanceOutput{})
	pulumi.RegisterOutputType(GetPrivateNetworkInstanceArrayOutput{})
	pulumi.RegisterOutputType(GetPrivateNetworkInstancePrivateIpConfigOutput{})
	pulumi.RegisterOutputType(GetPrivateNetworkInstancePrivateIpConfigArrayOutput{})
	pulumi.RegisterOutputType(GetPrivateNetworkInstancePrivateIpConfigV4Output{})
	pulumi.RegisterOutputType(GetPrivateNetworkInstancePrivateIpConfigV4ArrayOutput{})
	pulumi.RegisterOutputType(InstanceAddOnOutput{})
	pulumi.RegisterOutputType(InstanceAddOnArrayOutput{})
	pulumi.RegisterOutputType(InstanceAdditionalIpOutput{})
	pulumi.RegisterOutputType(InstanceAdditionalIpArrayOutput{})
	pulumi.RegisterOutputType(InstanceAdditionalIpV4Output{})
	pulumi.RegisterOutputType(InstanceAdditionalIpV4ArrayOutput{})
	pulumi.RegisterOutputType(InstanceIpConfigOutput{})
	pulumi.RegisterOutputType(InstanceIpConfigArrayOutput{})
	pulumi.RegisterOutputType(InstanceIpConfigV4Output{})
	pulumi.RegisterOutputType(InstanceIpConfigV4ArrayOutput{})
	pulumi.RegisterOutputType(InstanceIpConfigV6Output{})
	pulumi.RegisterOutputType(InstanceIpConfigV6ArrayOutput{})
	pulumi.RegisterOutputType(Object_storageAutoScalingOutput{})
	pulumi.RegisterOutputType(Object_storageAutoScalingArrayOutput{})
	pulumi.RegisterOutputType(Private_networkInstanceOutput{})
	pulumi.RegisterOutputType(Private_networkInstanceArrayOutput{})
	pulumi.RegisterOutputType(Private_networkInstancePrivateIpConfigOutput{})
	pulumi.RegisterOutputType(Private_networkInstancePrivateIpConfigArrayOutput{})
	pulumi.RegisterOutputType(Private_networkInstancePrivateIpConfigV4Output{})
	pulumi.RegisterOutputType(Private_networkInstancePrivateIpConfigV4ArrayOutput{})
}
