# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .get_image import *
from .get_instance import *
from .get_instance_snapshot import *
from .get_object_storage import *
from .get_object_storage_bucket import *
from .get_private_network import *
from .get_secret import *
from .image import *
from .instance import *
from .instance_snapshot import *
from .object_storage import *
from .object_storage_bucket import *
from .private_network import *
from .provider import *
from .secret import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_contabo.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_contabo.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "contabo",
  "mod": "index/image",
  "fqn": "pulumi_contabo",
  "classes": {
   "contabo:index/image:image": "Image"
  }
 },
 {
  "pkg": "contabo",
  "mod": "index/instance",
  "fqn": "pulumi_contabo",
  "classes": {
   "contabo:index/instance:instance": "Instance"
  }
 },
 {
  "pkg": "contabo",
  "mod": "index/instance_snapshot",
  "fqn": "pulumi_contabo",
  "classes": {
   "contabo:index/instance_snapshot:instance_snapshot": "Instance_snapshot"
  }
 },
 {
  "pkg": "contabo",
  "mod": "index/object_storage",
  "fqn": "pulumi_contabo",
  "classes": {
   "contabo:index/object_storage:object_storage": "Object_storage"
  }
 },
 {
  "pkg": "contabo",
  "mod": "index/object_storage_bucket",
  "fqn": "pulumi_contabo",
  "classes": {
   "contabo:index/object_storage_bucket:object_storage_bucket": "Object_storage_bucket"
  }
 },
 {
  "pkg": "contabo",
  "mod": "index/private_network",
  "fqn": "pulumi_contabo",
  "classes": {
   "contabo:index/private_network:private_network": "Private_network"
  }
 },
 {
  "pkg": "contabo",
  "mod": "index/secret",
  "fqn": "pulumi_contabo",
  "classes": {
   "contabo:index/secret:secret": "Secret"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "contabo",
  "token": "pulumi:providers:contabo",
  "fqn": "pulumi_contabo",
  "class": "Provider"
 }
]
"""
)
