// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetInstanceAddOn {
    id: string;
    quantity: number;
}

export interface GetInstanceAdditionalIpsV4 {
    gateway: string;
    ip: string;
    netmaskCidr: number;
}

export interface GetInstanceIpConfig {
    v4s: outputs.GetInstanceIpConfigV4[];
    v6s: outputs.GetInstanceIpConfigV6[];
}

export interface GetInstanceIpConfigV4 {
    gateway: string;
    ip: string;
    netmaskCidr: number;
}

export interface GetInstanceIpConfigV6 {
    gateway: string;
    ip: string;
    netmaskCidr: number;
}

export interface GetObjectStorageAutoScaling {
    errorMessage: string;
    sizeLimitTb: number;
    state: string;
}

export interface GetPrivateNetworkInstance {
    displayName: string;
    errorMessage: string;
    instanceId: string;
    name: string;
    privateIpConfigs: outputs.GetPrivateNetworkInstancePrivateIpConfig[];
    status: string;
}

export interface GetPrivateNetworkInstancePrivateIpConfig {
    v4s: outputs.GetPrivateNetworkInstancePrivateIpConfigV4[];
}

export interface GetPrivateNetworkInstancePrivateIpConfigV4 {
    gateway: string;
    ip: string;
    netmaskCidr: number;
}

export interface InstanceAddOn {
    id: string;
    quantity: number;
}

export interface InstanceAdditionalIp {
    v4s: outputs.InstanceAdditionalIpV4[];
}

export interface InstanceAdditionalIpV4 {
    gateway: string;
    ip: string;
    netmaskCidr: number;
}

export interface InstanceIpConfig {
    v4s: outputs.InstanceIpConfigV4[];
    v6s: outputs.InstanceIpConfigV6[];
}

export interface InstanceIpConfigV4 {
    gateway: string;
    ip: string;
    netmaskCidr: number;
}

export interface InstanceIpConfigV6 {
    gateway: string;
    ip: string;
    netmaskCidr: number;
}

export interface Object_storageAutoScaling {
    errorMessage?: string;
    sizeLimitTb?: number;
    state?: string;
}

export interface Private_networkInstance {
    displayName: string;
    errorMessage: string;
    instanceId: number;
    name: string;
    privateIpConfigs: outputs.Private_networkInstancePrivateIpConfig[];
    status: string;
}

export interface Private_networkInstancePrivateIpConfig {
    v4s: outputs.Private_networkInstancePrivateIpConfigV4[];
}

export interface Private_networkInstancePrivateIpConfigV4 {
    gateway: string;
    ip: string;
    netmaskCidr: number;
}

