// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getObjectStorage(args: GetObjectStorageArgs, opts?: pulumi.InvokeOptions): Promise<GetObjectStorageResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("contabo:index/getObjectStorage:getObjectStorage", {
        "autoScalings": args.autoScalings,
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getObjectStorage.
 */
export interface GetObjectStorageArgs {
    autoScalings?: inputs.GetObjectStorageAutoScaling[];
    id: string;
}

/**
 * A collection of values returned by getObjectStorage.
 */
export interface GetObjectStorageResult {
    readonly autoScalings: outputs.GetObjectStorageAutoScaling[];
    readonly cancelDate: string;
    readonly createdDate: string;
    readonly customerId: string;
    readonly dataCenter: string;
    readonly displayName: string;
    readonly id: string;
    readonly region: string;
    readonly s3TenantId: string;
    readonly s3Url: string;
    readonly status: string;
    readonly tenantId: string;
    readonly totalPurchasedSpaceTb: number;
}
export function getObjectStorageOutput(args: GetObjectStorageOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetObjectStorageResult> {
    return pulumi.output(args).apply((a: any) => getObjectStorage(a, opts))
}

/**
 * A collection of arguments for invoking getObjectStorage.
 */
export interface GetObjectStorageOutputArgs {
    autoScalings?: pulumi.Input<pulumi.Input<inputs.GetObjectStorageAutoScalingArgs>[]>;
    id: pulumi.Input<string>;
}
