// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getPrivateNetwork(args?: GetPrivateNetworkArgs, opts?: pulumi.InvokeOptions): Promise<GetPrivateNetworkResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("contabo:index/getPrivateNetwork:getPrivateNetwork", {
        "createdDate": args.createdDate,
        "description": args.description,
        "instanceIds": args.instanceIds,
        "name": args.name,
        "region": args.region,
        "regionName": args.regionName,
        "updatedAt": args.updatedAt,
    }, opts);
}

/**
 * A collection of arguments for invoking getPrivateNetwork.
 */
export interface GetPrivateNetworkArgs {
    createdDate?: string;
    description?: string;
    instanceIds?: number[];
    name?: string;
    region?: string;
    regionName?: string;
    updatedAt?: string;
}

/**
 * A collection of values returned by getPrivateNetwork.
 */
export interface GetPrivateNetworkResult {
    readonly availableIps: number;
    readonly cidr: string;
    readonly createdDate: string;
    readonly dataCenter: string;
    readonly description?: string;
    readonly id: string;
    readonly instanceIds?: number[];
    readonly instances: outputs.GetPrivateNetworkInstance[];
    readonly name?: string;
    readonly region?: string;
    readonly regionName: string;
    readonly updatedAt: string;
}
export function getPrivateNetworkOutput(args?: GetPrivateNetworkOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetPrivateNetworkResult> {
    return pulumi.output(args).apply((a: any) => getPrivateNetwork(a, opts))
}

/**
 * A collection of arguments for invoking getPrivateNetwork.
 */
export interface GetPrivateNetworkOutputArgs {
    createdDate?: pulumi.Input<string>;
    description?: pulumi.Input<string>;
    instanceIds?: pulumi.Input<pulumi.Input<number>[]>;
    name?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    regionName?: pulumi.Input<string>;
    updatedAt?: pulumi.Input<string>;
}
