// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSecret(args: GetSecretArgs, opts?: pulumi.InvokeOptions): Promise<GetSecretResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("contabo:index/getSecret:getSecret", {
        "createdAt": args.createdAt,
        "name": args.name,
        "type": args.type,
        "updatedAt": args.updatedAt,
        "value": args.value,
    }, opts);
}

/**
 * A collection of arguments for invoking getSecret.
 */
export interface GetSecretArgs {
    createdAt?: string;
    name: string;
    type: string;
    updatedAt?: string;
    value: string;
}

/**
 * A collection of values returned by getSecret.
 */
export interface GetSecretResult {
    readonly createdAt: string;
    readonly id: string;
    readonly name: string;
    readonly type: string;
    readonly updatedAt: string;
    readonly value: string;
}
export function getSecretOutput(args: GetSecretOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSecretResult> {
    return pulumi.output(args).apply((a: any) => getSecret(a, opts))
}

/**
 * A collection of arguments for invoking getSecret.
 */
export interface GetSecretOutputArgs {
    createdAt?: pulumi.Input<string>;
    name: pulumi.Input<string>;
    type: pulumi.Input<string>;
    updatedAt?: pulumi.Input<string>;
    value: pulumi.Input<string>;
}
