// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Instance_snapshot extends pulumi.CustomResource {
    /**
     * Get an existing Instance_snapshot resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: Instance_snapshotState, opts?: pulumi.CustomResourceOptions): Instance_snapshot {
        return new Instance_snapshot(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'contabo:index/instance_snapshot:instance_snapshot';

    /**
     * Returns true if the given object is an instance of Instance_snapshot.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Instance_snapshot {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Instance_snapshot.__pulumiType;
    }

    /**
     * The date when the snapshot will be autmatically deleted.
     */
    public /*out*/ readonly autoDeleteDate!: pulumi.Output<string>;
    /**
     * The creation date of this instance snapshot.
     */
    public readonly createdDate!: pulumi.Output<string>;
    /**
     * Description of this snapshot.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * Id of the Image the snapshot was taken from.
     */
    public /*out*/ readonly imageId!: pulumi.Output<string>;
    /**
     * Name of the Image the snapshot was taken from.
     */
    public /*out*/ readonly imageName!: pulumi.Output<string>;
    /**
     * Instance identifier associated with the snapshot.
     */
    public readonly instanceId!: pulumi.Output<number | undefined>;
    /**
     * Name of the snapshot.
     */
    public readonly name!: pulumi.Output<string>;

    /**
     * Create a Instance_snapshot resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: Instance_snapshotArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: Instance_snapshotArgs | Instance_snapshotState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as Instance_snapshotState | undefined;
            resourceInputs["autoDeleteDate"] = state ? state.autoDeleteDate : undefined;
            resourceInputs["createdDate"] = state ? state.createdDate : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["imageId"] = state ? state.imageId : undefined;
            resourceInputs["imageName"] = state ? state.imageName : undefined;
            resourceInputs["instanceId"] = state ? state.instanceId : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
        } else {
            const args = argsOrState as Instance_snapshotArgs | undefined;
            resourceInputs["createdDate"] = args ? args.createdDate : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["instanceId"] = args ? args.instanceId : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["autoDeleteDate"] = undefined /*out*/;
            resourceInputs["imageId"] = undefined /*out*/;
            resourceInputs["imageName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Instance_snapshot.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering instance_snapshot resources.
 */
export interface Instance_snapshotState {
    /**
     * The date when the snapshot will be autmatically deleted.
     */
    autoDeleteDate?: pulumi.Input<string>;
    /**
     * The creation date of this instance snapshot.
     */
    createdDate?: pulumi.Input<string>;
    /**
     * Description of this snapshot.
     */
    description?: pulumi.Input<string>;
    /**
     * Id of the Image the snapshot was taken from.
     */
    imageId?: pulumi.Input<string>;
    /**
     * Name of the Image the snapshot was taken from.
     */
    imageName?: pulumi.Input<string>;
    /**
     * Instance identifier associated with the snapshot.
     */
    instanceId?: pulumi.Input<number>;
    /**
     * Name of the snapshot.
     */
    name?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Instance_snapshot resource.
 */
export interface Instance_snapshotArgs {
    /**
     * The creation date of this instance snapshot.
     */
    createdDate?: pulumi.Input<string>;
    /**
     * Description of this snapshot.
     */
    description?: pulumi.Input<string>;
    /**
     * Instance identifier associated with the snapshot.
     */
    instanceId?: pulumi.Input<number>;
    /**
     * Name of the snapshot.
     */
    name?: pulumi.Input<string>;
}
