// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Object_storage_bucket extends pulumi.CustomResource {
    /**
     * Get an existing Object_storage_bucket resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: Object_storage_bucketState, opts?: pulumi.CustomResourceOptions): Object_storage_bucket {
        return new Object_storage_bucket(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'contabo:index/object_storage_bucket:object_storage_bucket';

    /**
     * Returns true if the given object is an instance of Object_storage_bucket.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Object_storage_bucket {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Object_storage_bucket.__pulumiType;
    }

    /**
     * The creation date of the bucket.
     */
    public /*out*/ readonly creationDate!: pulumi.Output<string>;
    /**
     * The name of your bucket, consider the naming restriction
     * https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The contabo objectStorageId on which the bucket should be created.
     */
    public readonly objectStorageId!: pulumi.Output<string>;
    /**
     * Choose the access to your bucket. You can not share it at all or share it publicly.
     */
    public readonly publicSharing!: pulumi.Output<boolean | undefined>;
    /**
     * If your bucket is publicly shared, you can access it with this link.
     */
    public /*out*/ readonly publicSharingLink!: pulumi.Output<string>;

    /**
     * Create a Object_storage_bucket resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: Object_storage_bucketArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: Object_storage_bucketArgs | Object_storage_bucketState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as Object_storage_bucketState | undefined;
            resourceInputs["creationDate"] = state ? state.creationDate : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["objectStorageId"] = state ? state.objectStorageId : undefined;
            resourceInputs["publicSharing"] = state ? state.publicSharing : undefined;
            resourceInputs["publicSharingLink"] = state ? state.publicSharingLink : undefined;
        } else {
            const args = argsOrState as Object_storage_bucketArgs | undefined;
            if ((!args || args.objectStorageId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'objectStorageId'");
            }
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["objectStorageId"] = args ? args.objectStorageId : undefined;
            resourceInputs["publicSharing"] = args ? args.publicSharing : undefined;
            resourceInputs["creationDate"] = undefined /*out*/;
            resourceInputs["publicSharingLink"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Object_storage_bucket.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering object_storage_bucket resources.
 */
export interface Object_storage_bucketState {
    /**
     * The creation date of the bucket.
     */
    creationDate?: pulumi.Input<string>;
    /**
     * The name of your bucket, consider the naming restriction
     * https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html.
     */
    name?: pulumi.Input<string>;
    /**
     * The contabo objectStorageId on which the bucket should be created.
     */
    objectStorageId?: pulumi.Input<string>;
    /**
     * Choose the access to your bucket. You can not share it at all or share it publicly.
     */
    publicSharing?: pulumi.Input<boolean>;
    /**
     * If your bucket is publicly shared, you can access it with this link.
     */
    publicSharingLink?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Object_storage_bucket resource.
 */
export interface Object_storage_bucketArgs {
    /**
     * The name of your bucket, consider the naming restriction
     * https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html.
     */
    name?: pulumi.Input<string>;
    /**
     * The contabo objectStorageId on which the bucket should be created.
     */
    objectStorageId: pulumi.Input<string>;
    /**
     * Choose the access to your bucket. You can not share it at all or share it publicly.
     */
    publicSharing?: pulumi.Input<boolean>;
}
