// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the contabo package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'contabo';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Provider.__pulumiType;
    }

    /**
     * The api endpoint is https://api.contabo.com.
     */
    public readonly api!: pulumi.Output<string | undefined>;
    /**
     * Your oauth2 client id can be found in the [Customer Control Panel](https://new.contabo.com/account/security) under the
     * menu item account secret.
     */
    public readonly oauth2ClientId!: pulumi.Output<string | undefined>;
    /**
     * Your oauth2 client secret can be found in the [Customer Control Panel](https://new.contabo.com/account/security) under
     * the menu item account secret.
     */
    public readonly oauth2ClientSecret!: pulumi.Output<string | undefined>;
    /**
     * API Password (this is a new password which you'll set or change in the [Customer Control
     * Panel](https://new.contabo.com/account/security) under the menu item account secret.)
     */
    public readonly oauth2Pass!: pulumi.Output<string | undefined>;
    /**
     * The oauth2 token url is https://auth.contabo.com/auth/realms/contabo/protocol/openid-connect/token.
     */
    public readonly oauth2TokenUrl!: pulumi.Output<string | undefined>;
    /**
     * API User (your email address to login to the [Customer Control Panel](https://new.contabo.com/account/security) under
     * the menu item account secret.
     */
    public readonly oauth2User!: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["api"] = args ? args.api : undefined;
            resourceInputs["oauth2ClientId"] = (args ? args.oauth2ClientId : undefined) ?? utilities.getEnv("CONTABO_OAUTH2_CLIENT_ID");
            resourceInputs["oauth2ClientSecret"] = (args ? args.oauth2ClientSecret : undefined) ?? utilities.getEnv("CONTABO_OAUTH2_CLIENT_SECRET");
            resourceInputs["oauth2Pass"] = (args ? args.oauth2Pass : undefined) ?? utilities.getEnv("CONTABO_OAUTH2_PASS");
            resourceInputs["oauth2TokenUrl"] = args ? args.oauth2TokenUrl : undefined;
            resourceInputs["oauth2User"] = (args ? args.oauth2User : undefined) ?? utilities.getEnv("CONTABO_OAUTH2_USER");
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * The api endpoint is https://api.contabo.com.
     */
    api?: pulumi.Input<string>;
    /**
     * Your oauth2 client id can be found in the [Customer Control Panel](https://new.contabo.com/account/security) under the
     * menu item account secret.
     */
    oauth2ClientId?: pulumi.Input<string>;
    /**
     * Your oauth2 client secret can be found in the [Customer Control Panel](https://new.contabo.com/account/security) under
     * the menu item account secret.
     */
    oauth2ClientSecret?: pulumi.Input<string>;
    /**
     * API Password (this is a new password which you'll set or change in the [Customer Control
     * Panel](https://new.contabo.com/account/security) under the menu item account secret.)
     */
    oauth2Pass?: pulumi.Input<string>;
    /**
     * The oauth2 token url is https://auth.contabo.com/auth/realms/contabo/protocol/openid-connect/token.
     */
    oauth2TokenUrl?: pulumi.Input<string>;
    /**
     * API User (your email address to login to the [Customer Control Panel](https://new.contabo.com/account/security) under
     * the menu item account secret.
     */
    oauth2User?: pulumi.Input<string>;
}
