# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

api: Optional[str]
"""
The api endpoint is https://api.contabo.com.
"""

oauth2ClientId: Optional[str]
"""
Your oauth2 client id can be found in the [Customer Control Panel](https://new.contabo.com/account/security) under the
menu item account secret.
"""

oauth2ClientSecret: Optional[str]
"""
Your oauth2 client secret can be found in the [Customer Control Panel](https://new.contabo.com/account/security) under
the menu item account secret.
"""

oauth2Pass: Optional[str]
"""
API Password (this is a new password which you'll set or change in the [Customer Control
Panel](https://new.contabo.com/account/security) under the menu item account secret.)
"""

oauth2TokenUrl: Optional[str]
"""
The oauth2 token url is https://auth.contabo.com/auth/realms/contabo/protocol/openid-connect/token.
"""

oauth2User: Optional[str]
"""
API User (your email address to login to the [Customer Control Panel](https://new.contabo.com/account/security) under
the menu item account secret.
"""

